### ISSUE TITLE
[São Bernardo do Campo] FEMUG-ABC #7 Clojure + Javascript + React

### ISSUE THREAD

**Issue by theandersonn** [frontendbr/eventos#1]
**Título:** FEMUG-ABC #7 Clojure + Javascript + React

**Data:** 20/02/2016, 10h - 12h

**Local:** R. Frei Gáspar, 941 - Vila Santa Rita de Cassia, São Bernardo do Campo - SP

**Descrição:** O encontro será em formato de talk com o Ricardo Sato, que vai falar um pouco sobre a Stack usada na NuBank e Clojure + Javascript + React.

**Valor:** Gratuito

[Mais informações](http://abc.femug.com/t/femug-abc-7-clojure-javascript-react/99)

**Comment by eduardojmatos** [comment]
:+1:
