### ISSUE TITLE
[São Paulo ] Meetup HTML SP #2 

### ISSUE THREAD

**Issue by theandersonn** [frontendbr/eventos#101]
**Título**: Meetup HTML SP #2
  
**Data**: 05 de setembro

**Local**: Yahoo Brasil - Avenida Brigadeiro Faria Lima, 3600 - , São Paulo

**Descrição (breve)**: O HTML São Paulo vem com o objetivo de debatermos e trocarmos experiências sobre Front-End.

**Valor**: Gratuito

**Mais informações**: http://www.meetup.com/pt-BR/html-sp/events/233576242/?eventId=233576242

**Comment by elvisdetona** [comment]
evento já passou.

**Comment by theandersonn** [comment]
@elvisdetona Valeu :+1: Fechando.
No json faço a remoção a noite, ou se for possível outro colaborador antes.

**Comment by LFeh** [comment]
Done!
