### ISSUE TITLE
FrontendBR + FrontUX Beer

### ISSUE THREAD

**Issue by matmarsiglio** [frontendbr/eventos#105]
**Título**:  FrontendBR + FrontUX Beer
  
**Data**: 15/09/2016

**Local**: bar C* do Padre https://goo.gl/maps/vroFesrBaax

**Descrição (breve)**: Dia 15/09 vai acontecer o FrontUX Beer (logo mais links de divulgação) e já que somos comunidade, ja que a gente constroi sáite nessa porra, vamos juntar os roles e fazer um FrontendBR + FrontUX Beer. YAY!

**Valor**: Apenas apareça e pague o que consumir! \o/

**Mais informações**: Mais informações na tread de discussão do evento: https://github.com/frontendbr/forum/issues/291

**Comment by LFeh** [comment]
Lindo :heart:

**Comment by felipeuntill** [comment]
Eu supostamente tinha parado de Beber 🤔

**Comment by danilomelo** [comment]
E quem não bebe pode ir tbm? :P

**Comment by LFeh** [comment]
@danilomelo Claro! Sempre tem suco :dancers:
