### ISSUE TITLE
[Fortaleza] Conferência de JavaScript do Ceará

### ISSUE THREAD

**Issue by cjpatoilo** [frontendbr/eventos#11]
**Título**: Conferência de JavaScript do Ceará
  
**Data**: Sábado, 28 de Maio de 2016

**Local**: Av. Alm. Maximiano da Fonseca, 1395 - Eng. Luciano Cavalcante, 60811-020 - Fortaleza - CE

**Descrição**: O CEJS é um evento da comunidade para a comunidade.

**Valor**: R$120,00

**Mais informações**: http://www.cejs.com.br/

cc/ @cmilfont @henriquegogo @marcelodeveloper

**Comment by cmilfont** [comment]
+1  :D

**Comment by marcelodeveloper** [comment]
+1 =)

**Comment by henriquegogo** [comment]
+1 :dancer:

**Comment by eduardojmatos** [comment]
@cjpatoilo  massa! :+1:
