### ISSUE TITLE
[Barueri] Meetup Alphaville #1

### ISSUE THREAD

**Issue by renatogalvones** [frontendbr/eventos#115]
**Título**: Meetup Alphaville
  
**Data**: 05/10/2016

**Local**: Catho - Alameda Juari, 262, Tamboré - Barueri

**Descrição (breve)**: Esse é um grupo para discussão sobre desenvolvimento web em geral, focado em qualidade e performance. Neste evento teremos a talk do Luiz Kota: "Desenvolvimento Front-end em times grandes"  

**Valor**: Free - 0800 - Na faixa

**Mais informações**: https://www.meetup.com/Meetup-Alphaville/events/234302440/

**Comment by renatogalvones** [comment]
@theandersonn @LFeh o link no https://frontendbr.github.io/eventos/ tá marcando o DFUX Litoral.

Acho q deu alguma zica. Vou tentar descobrir.

**Comment by theandersonn** [comment]
@renatogalvones Fiz uma pequena confusão com o link do outro evento que vai rolar em Santos [foi mal].
Dei merge no seu PR #116 mas tem que rolar o deploy tbm pra atualizar o site, vejo até a noite, ok? Aqui na Agência não tenho o projeto ambientado.

**Comment by renatogalvones** [comment]
@theandersonn Imaginei q fosse algo parecido mesmo. Pega nada.

Valeu mano!

:metal:

**Comment by theandersonn** [comment]
@renatogalvones Ajuste feito. Obrigado por compartilhar o evento. :smiley:
