### ISSUE TITLE
[Site] Em localhost o efeito blur das thumbs estão desregulados

### ISSUE THREAD

**Issue by theandersonn** [frontendbr/eventos#117]
Aqui pra mim [localhost] as thumbs estão 'doidas', ficam piscando ou totalmente embaçadas; na versão online funciona de boa.

Sugestões?

**Comment by fdaciuk** [comment]
Tem alguma coisa atualizando o estado da aplicação e todo o momento. Sabe se foi mexido em algo no código? Vou tentar dar uma investigada.

**Comment by theandersonn** [comment]
No código não.
Esse comportamento começou depois daquele dia que subi o projeto sem instalar o 'Preact', em seguida atualizei, o site voltou mas as thumbs ficarão com esse comportamento em localhost.

**Comment by fdaciuk** [comment]
Eu vi aqui :|
Parece que o Preact está com algum problema pra funcionar junto com o hot loader. Vou fazer mais uns testes depois. Por enquanto, voltei com om React só em dev, e deixei o Preact em prod.

Tudo certo novamente =)

**Comment by theandersonn** [comment]
Já atualizei aqui e 100% ok :)
