### ISSUE TITLE
DevParaná Conference 2016

### ISSUE THREAD

**Issue by theandersonn** [frontendbr/eventos#118]
**Título**: DevParaná Conference 2016

**Data**: 26 de Novembro

**Local**: Sebrae Maringá - Avenida Bento Munhoz da Rocha Neto - Zona 7, Maringá - PR

**Descrição (breve)**: O DevParaná Conference 2016 vai trazer palestrantes que são influência nacional em sua área de atuação, também como dará oportunidade a comunidade apresentar o que sabe fazer de melhor. Serão 8 talks de ótima qualidade, um dia inteiro de pura imersão em tecnologia!

**Valor**: A partir de R$ 65,00

**Mais informações**:  https://www.eventick.com.br/devparana-conference-2016

**Comment by ferfabricio** [comment]
@theandersonn teria como adicionar a logo do DevParaná?

![8ddlporn](https://cloud.githubusercontent.com/assets/697486/19818233/9b9eab6c-9d2d-11e6-8107-99f6d77960f0.png)

**Comment by theandersonn** [comment]
Tem sim, claro!

**Comment by ferfabricio** [comment]
Vlw!

**Comment by theandersonn** [comment]
@ferfabricio Update feito!

**Comment by ferfabricio** [comment]
Muito obrigado @theandersonn
