### ISSUE TITLE
[São Paulo] Jurassic JavaScript Park - Construindo Aplicações Offline

### ISSUE THREAD

**Issue by anacmdo** [frontendbr/eventos#125]
**Título**: JURASSIC JAVASCRIPT PARK - CONSTRUINDO APLICAÇÕES OFFLINE 
  
**Data**: 27.10

**Local**: Germinadora - Santa Cruz - São Paulo

**Descrição (breve)**: O curso ensinará formas de transformar aplicações e sites para que funcionem mesmo sem acesso à internet, apresentando maneiras de armazenar informação utilizando as API's do JavaScript. O objetivo será compreender a utilização dessas aplicações, realizar testes em páginas da internet e por em prática as funcionalidades aprendidas através de dinâmicas propostas pelo facilitador.

**Logotipo do evento**: 
![plataforma](https://cloud.githubusercontent.com/assets/22508009/18932691/f66bc446-85a7-11e6-8e8d-665a5071d66b.jpg)

**Valor**: R$110 (1º Lote) e R$130 (2º Lote) 

**Mais informações**: http://www.coletividad.org/events/jurassic-javascript-park-construindo-aplicacoes-offline

**Comment by theandersonn** [comment]
@frontendbr/adminevents, @frontendbr/admins Esse é o primeiro Workshop que temos divulgado aqui, qual é a opinião de vcs?

Eu não vejo problemas, desde seja presencial e relacionado a front-end.

E vcs ?

**Comment by fdaciuk** [comment]
Acho válido esses pontos @theandersonn. Podemos tomar como base, e até adicionar no README pra ficar claro =)

**Comment by diogomoretti** [comment]
Acho válido, talvez a ponto de não colocar no JSON. Mas vou mudar o título para ficar no padrão.

**Comment by eduardojmatos** [comment]
Eu sou suspeito de falar desse, deixo pra vocês decidirem o que é melhor :)

**Comment by kavalcante** [comment]
Acho muito bom, evento é evento, sempre bom! :)

**Comment by theandersonn** [comment]
Tá falado :punch:

**Comment by LFeh** [comment]
Totalmente a favor \o
