### ISSUE TITLE
[Site] Ícones estão quebrando site

### ISSUE THREAD

**Issue by theandersonn** [frontendbr/eventos#128]
Abri o site agora e os ícones estão quebrando o site, houve alguma mudança de ontem pra hoje?

![print-eventos](https://cloud.githubusercontent.com/assets/5203138/18992316/0de49a60-86f4-11e6-948e-bea6da06c0c3.jpg)

**Comment by LFeh** [comment]
@fdaciuk Acabei de inspecionar, e o problema é que os ícones estão vindo com `className` ao invés de `class`. Provavelmente deu algum problema na compilação.

Como sabe, não consigo fazer o deploy aqui. huahaha

Faz ai?

**Comment by fdaciuk** [comment]
@frontendbr/adminevents galera, antes de fazer deploy, rode sempre `npm run build`, e suba o conteúdo da pasta `build` na sua máquina local **antes** de fazer deploy, pra garantir que está tudo ok, blz?

Por mais que seja um projeto open source, não pra deixar esse tipo de coisa acontecer.

Valeu por reportar @theandersonn! Já buildei e subi novamente aqui @LFeh =)

**Comment by LFeh** [comment]
Valeu @fdaciuk e @theandersonn!
