### ISSUE TITLE
[São Paulo] Frontinsampa 2016 - Edição especial de 5 anos!

### ISSUE THREAD

**Issue by elvisdetona** [frontendbr/eventos#13]
**Título**: Frontinsampa 2016
  
**Data**: 02 de Julho de 2016 - 9h00

**Local**: Teatro do Colégio Maria Imaculada
Endereço: Av. Bernardino de Campos, 79 - Paraiso - São Paulo/SP (ao lado do shopping paulista)

**Descrição (breve)**:  Stairway to Heaven
Calma, não vamos falar de Led Zeppelin por aqui... A novidade é que o Frontinsampa  deixou o Inferno e pegou a escada para o Paraíso, literalmente. A 5ª edição será especial, num teatro para quase 400 pessoas, com uma ótima localização e com a tradição de trazer ótimas palestras e também muito networking, afinal, o lema do frontinsampa é Aprender, Compartilhar e se Divertir.

**Valor**: R$ 300,00 (Lote Final).
[http://www.frontinsampa.com.br](http://www.frontinsampa.com.br)

**DICA**: Se vc vier para o frontinsampa e não é aqui de SP, a DICA é: Esteja em SP sexta feira na hora do HH para participar do Code In The Dark Brasil :+1: 

**Mais informações**: 
Site: www.frontinsampa.com.br
Facebook: http://facebook.com/frontinsampa
Twitter: [@frontinsp](http://twitter.com/frontinsp)
Instagram: [frontinsampa](https://instagram.com/frontinsampa/)
Youtube: http://youtube.com/frontinsampa
frontinsampa@gmail.com

**Comment by LFeh** [comment]
\o/

**Comment by femontanha** [comment]
We are going to "Paradise City" :metal: 
https://www.youtube.com/watch?v=Rbm6GXllBiw

**Comment by felipetrova** [comment]
Perdi a edição do ano passado :disappointed:, mas nessa pretendo ir :smiley:
Vai rolar open? :stuck_out_tongue_closed_eyes: :beer:

**Comment by BielRibeiro** [comment]
Booora!

**Comment by eduardojmatos** [comment]
Ahhhuuuuuuu como diria o @elvisdetona

**Comment by elvisdetona** [comment]
O evento vai ser num teatro... lá não pode fazer muita coisa, mas "quem sabe"!??!?! Não podemos dizer nem que sim e nem que não. :smile:  :beers:  @felipetrova

**Comment by elvisdetona** [comment]
Ah... se quer pagar BARATO, aproveite o lote de lançamento e também o primeiro lote!

**Comment by LFeh** [comment]
Bar depois e já era. Estamos do lado do fervo =)

**Comment by willianjusten** [comment]
Será que vai ser dessa vez que eu consigo ir? =)

**Comment by danielfilho** [comment]
do inferno pra um colégio religioso. curti! :grin:

**Comment by victormiguez** [comment]
Frontinsampa é sempre do caralho, ingresso garantido! :metal:

**Comment by suissa** [comment]
Não tem como perder!

**Comment by elvisdetona** [comment]
@fdaciuk  @LFeh Os dados do frontinsampa estao pegando de algum lugar ou ta estattico? 
O Fialho me passou uma url para testar e os dados do frontinsampa estao bem antigos. :(

https://frontendbr.github.io/eventos/

**Comment by fdaciuk** [comment]
@elvisdetona só mandar pr no `src/data/events.json` atualizando =)

**Comment by elvisdetona** [comment]
atualizei la! :metal:
