### ISSUE TITLE
[Sorocaba] - 1º CodePen Meetup Brasil

### ISSUE THREAD

**Issue by amandavilela** [frontendbr/eventos#133]
**Título**: 1º CodePen Meetup Brasil
  
**Data**: 22/10/2016

**Local**: Sorocaba/SP

**Descrição (breve)**: Show & Tell, Dribbble + CodePen cross-overs e um coffee bem legal pra fazermos novas amizades e compartilharmos conhecimento.

**Logotipo do evento:**: http://i.imgur.com/1JFeQuP.jpg

**Valor**: Gratuito

**Mais informações**: https://nvite.com/CodePenSorocaba/

**Comment by felipebernardes** [comment]
uhuuuuuuu!!!
