### ISSUE TITLE
  [Porto Alegre] 4º edição do FrontInPoa

### ISSUE THREAD

**Issue by gabrielsixel** [frontendbr/eventos#135]
**Título**:  [Porto Alegre] 4º edição do FrontInPoa

**Data**: 10/12/2016 08:40

**Local**: Rua Cel. Genuíno, 130

**Descrição (breve)**:
Evento de tecnologia de desenvolvimento Web que ocorre em Porto Alegre. Visite também nosso Twitter: http://twitter.com/frontinpoa
**Logotipo do evento:**  

**Valor**: 
Primeiro Lote R$79,00 Disponível até 25/10

**Mais informações**: 
http://frontinpoa.com.br/2016/

**Comment by theandersonn** [comment]
@gabrielsixel Fiz um pequeno update na data pra '10/12/2016', ok?

**Comment by gabrielsixel** [comment]
@theandersonn Ok, acho que escapou! :stuck_out_tongue:

**Comment by gabrielsixel** [comment]
Estou fazendo o PR em alguns minutos.

**Comment by theandersonn** [comment]
PR pra inserir no json?

Além de inserir em 'eventos/src/data/events.json'
tem que fazer deploy. seguindo essas [infos](https://github.com/frontendbr/eventos/blob/develop/CONTRIBUTING.md). Qualquer dúvida é só falar.

**Comment by gabrielsixel** [comment]
@theandersonn não entendi. No link que vc me passou diz:
5 - Após atualizar o JSON, suba o projeto localmente e verifique se está tudo correto;
6 - Envie um pull request na branch develop e marque algum dos administradores da organização, para que alguém possa validar e fazer o merge;

Faltou alguma etapa? Errei alguma coisa? (eu sou iniciante mesmo e não entendo muito de Gulp)

**Comment by felipeuntill** [comment]
@theandersonn Ele não vai poder fazer o processo de deploy por não ser um administrador do grupo

**Comment by theandersonn** [comment]
Esse detalhe acabou que despercebi, somente admin consegue fazer o deploy, né?

Então @gabrielsixel o que você fez está correto. O primeiro admin que puder irá mergear o seu PR e fazer o deploy pra atualizar o site.

Obrigado por compartilhar o evento com a comunidade.

**Comment by gabrielsixel** [comment]
:+1: Eu que agradeço!
