### ISSUE TITLE
[Brasília] DevBRasília #01

### ISSUE THREAD

**Issue by rodrigocipriani** [frontendbr/eventos#138]
**Título**: [Brasília] DevBrasília #01

**Data**: A definir

**Local**: A definir

**Descrição (breve)**: Pessoal, eu sou de Florianópolis mas moro em Brasília, e pensei em fazer um encontro por aqui. Não tenho experiências nos encontros mas acho que seria bem interessante.
Podemos usar esse canal para definir algo?

**Logotipo do evento:**: A definir

**Valor**: Grátis

**Mais informações**: A definir

**Comment by theandersonn** [comment]
Fala @rodrigocipriani! Que maneiro a vibe!

Sim, pode utilizar o canal; pelo fluxo de como as coisas acontecem eu acho que no repositório '[frontendbr/forum](https://github.com/frontendbr/forum/issues)' mais pessoas terão acesso. E também no [slack Front-End BR](http://frontendbrasil.slack.com/).

Já tem um local onde a galera poderá se encontrar? Se sim, já abre um página no [meetup.com](http://www.meetup.com/pt-BR/) e já agita o primeiro encontro, o pessoal vai animando, vai pilhando e as coisas vão acontecer.

**Comment by christian2212** [comment]
@rodrigocipriani  Tambem sou de Brasília Acho muito boa essa iniciativa, Brasília esta carente de meetups, encontros e eventos.

**Comment by rodrigocipriani** [comment]
Legal, vamos ver se temos mais interessados então. Novembro estarei viajando, então provavelmente não responderei aqui. Mas assim que voltar vou continuar.

**Comment by theandersonn** [comment]
Pessoal pra manter a organização aqui no repo estarei fechando essa issue, quando desejarem dar continuidade a discussão só falar que reabrimos ou podem utilizar outros canais da comunidade.
