### ISSUE TITLE
[São Paulo] Meetup CSS 14

### ISSUE THREAD

**Issue by raphaelfabeni** [frontendbr/eventos#14]
**Título**: Meetup CSS 14
  
**Data**: 22/03/2016

**Local**: Just Digital - _Rua Enxovia, 472 - Vila São Francisco, São Paulo - SP_

**Descrição (breve)**: Nessa edição teremos uma talk do Wellington Dutra sobre SMACSS e BEM. 

**Valor**: Grátis

**Mais informações**: Através do [repositório no Github](https://github.com/raphaelfabeni/css-sp) ou da [página da edição no site do meetup](http://bit.ly/meetup-css-14).

![meetup-14](https://cloud.githubusercontent.com/assets/1345662/13725475/c7041938-e881-11e5-9dcb-8efc2953fd50.png)

**Comment by LFeh** [comment]
\o/

**Comment by raphaelfabeni** [comment]
:metal:

**Comment by LFeh** [comment]
Foi ótimo!
