### ISSUE TITLE
[Rio de Janeiro] Front in Rio 2016 HTML Edition

### ISSUE THREAD

**Issue by theandersonn** [frontendbr/eventos#15]
**Título**: Front in Rio 2016 HTML Edition
  
**Data**: 14 de Maio

**Local**: UNIRIO - Avenida Pasteur 296 

**Descrição**: Palestras sobre HTML5 API's, acessibilidade, semântica, patterns e performance.

**Valor**: Até o dia 06/05 primeiro lote R$50,00, Após R$ 70,00

**Mais informações**: http://frontinrio.com.br/

**Comment by LFeh** [comment]
Porra, show de bola!

**Comment by theandersonn** [comment]
Editando a descrição, a data passou para 14 de maio... agora vai :metal:

**Comment by willianjusten** [comment]
Agora vai! =D

**Comment by willianjusten** [comment]
Agora vai! =D

**Comment by willianjusten** [comment]
Agora vai! =D

**Comment by fdaciuk** [comment]
Já foi também né?
