### ISSUE TITLE
Licença deste projeto

### ISSUE THREAD

**Issue by gabriel-ribeiro-ir** [frontendbr/eventos#155]
Pessoal, estamos reorganizando nosso grupo de meetup aqui de Campinas e pensamos em forkar este repositório para fazer um site.
Como não achei a licença, estou abrindo esta issue para pedir a permissão de vocês.

**Comment by theandersonn** [comment]
@frontendbr/adminevents, @frontendbr/admins

**Comment by fdaciuk** [comment]
Mancada, foi mal @gabriel-ribeiro-ir. Mas o projeto é open source, vamos usar [MIT](https://opensource.org/licenses/MIT), vou adicionar no README =)

Pode forkar e usar à vontade. Só, por favor, mantenha a fonte no rodapé do site =)

**Comment by Mendrone** [comment]
Cara acho que nesse caso posso falar por todos: Manda ver! 

Creio que o @fdaciuk e o @diogorodrigues que foram os caras que ficaram a frente do site (implementação e design) vão curtir pra caralho. 

@frontendbr/admins poderíamos colocar a licença como MIT não?

**Comment by fdaciuk** [comment]
Estamos conectados @Mendrone haha :heart:

**Comment by Mendrone** [comment]
Aee HAHAHAHAHA ❤️

**Comment by fdaciuk** [comment]
Pronto, agora tem licença @gabriel-ribeiro-ir! Obrigado por avisar :heart: :dancer: :dancer: :sparkles:

**Comment by fdaciuk** [comment]
E aproveitando: @theandersonn, obrigado por fazer a intermediação.. está fazendo um ótimo trabalho aqui, parabéns :heart: :sparkles:

**Comment by eduardojmatos** [comment]
Boa @gabriel-ribeiro-ir !!! :)

**Comment by diogorodrigues** [comment]
Boaaa. Super fechado!

Em seg, 5 de dez de 2016 11:30, Eduardo Matos <notifications@github.com>
escreveu:

**Comment by LFeh** [comment]
O @theandersonn pegou pra ele esse repositorio e esta fazendo um trampo absurdo! Só elogios 😸 

E claro, MIT, fonte no rodapé e ja era!

Sucesso @gabriel-ribeiro-ir ;)

**Comment by gabriel-ribeiro-ir** [comment]
Valeuu pela resposta pessoal! Forkado e estamos customizando.
Pode deixar que a fonte e o link para o fórum estarão lá.
