### ISSUE TITLE
[São Paulo] Front in Sampa 2017

### ISSUE THREAD

**Issue by theandersonn** [frontendbr/eventos#156]
**Título**: Front in Sampa 2017
  
**Data**: 01 jul 2017 

**Local**: Teatro do Colégio Maria Imaculada

**Logotipo do evento:**: https://cloud.githubusercontent.com/assets/5203138/21165552/258446f2-c187-11e6-9bb9-d51828c99017.jpg

**Descrição (breve)**: Conteúdo relevante e atualizado, bate-papo com profissionais da área, networking e aquele pós-evento que ninguém quer perder.

**Valor**: A partir de R$90,00

**Mais informações**: http://www.frontinsampa.com.br/

**Comment by LFeh** [comment]
c/c @elvisdetona

**Comment by theandersonn** [comment]
@elvisdetona Aproveritando, se possível nos ajude com uma descrição curta para o evento.

**Comment by elvisdetona** [comment]
**Local:** Teatro do hotel Maksoud Plaza.

**Descrição:** No final do #frontinsampa 2016 e uns dias atrás, publicamos que o evento do ano que vem seria realizado novamente no Inferno, na Rua Augusta, mas como diria o brother Ozzy Osbourne “I'm going through changes”.... Mudança de planos! 

Devido ao feedback tão positivo do pessoal sobre o evento no Teatro... do Colégio Maria Imaculada, no bairro do Paraíso, decidimos realizar o Frontinsampa 2017 novamente no local, mas... devido algumas solicitações e a necessidade de um lugar maior e com uma infra-estrutura melhor, mudamos novamente e escolhemos o Teatro do hotel Maksoud Plaza, (aproximadamente 500 participantes) que está localizado a uma quadra da Paulista, a avenida mais importante de São Paulo, e próximo à efervescente vida cultural e gastronômica da capital paulistana. Convenientemente localizado no centro financeiro da cidade, o hotel tem fácil acesso aos aeroportos de Guarulhos e Congonhas.

Todavia, entretanto, porém, contudo e não obstante, já estamos acertando detalhes para a festa pós-evento. Ainda é segredo, mas logo mais publicaremos o local da confraternização.


**Logotipo do evento:**
![logo-frontinsampa-white2017](https://cloud.githubusercontent.com/assets/1714296/21594300/23f7a5d2-d108-11e6-8b31-30dd197a40b3.png)

**Informações adicionais:** Nós vamos atualizando o site e tb pelas redes sociais... temos 2 palestrantes confirmados: Raphael Fabeni (**MeetupCSS / Red Ventures**) e Fábio Vedovelli (**Octimine GmbH - Munique/Alemanha e entusiasta Vue.js**). E quem vai apresentar este ano é o Matheus Marsiglio (**FrontUX / Evino**)

**Comment by LFeh** [comment]
@theandersonn Consegue atualizar com essa descrição nova que o @elvisdetona enviou?

**Comment by theandersonn** [comment]
@LFeh Consigo sim!
Faço a noite, aqui na agência não tenho o ambiente do site montado.

**Comment by theandersonn** [comment]
Update feito.

**Comment by LFeh** [comment]
Monstro
