### ISSUE TITLE
[São Paulo] CodeintheDarkBR 2017

### ISSUE THREAD

**Issue by theandersonn** [frontendbr/eventos#161]
**Título**:  CodeintheDarkBR 2017
  
**Data**: 10 de Março/2017

**Local**: Rua Oscar Freire, 2379

**Descrição (breve)**: Vários desenvolvedores(as) front-end precisam codificar uma página em apenas 15 minutos... Até aí o desafio já é enorme, concorda? Agora adicione o fato de que eles(as) não podem ver o resultado da página no browser, somente o código fonte, usando apenas HTML e CSS: Esse é o Code in the Dark!

**Logotipo do evento:**: https://cloud.githubusercontent.com/assets/5203138/22705484/d29d44c8-ed52-11e6-918b-0ffc0ef95002.jpg

**Valor**: Free 

**Mais informações**: http://codeinthedark.com.br/

**Comment by LFeh** [comment]
Épico.
