### ISSUE TITLE
[Porto Alegre] RSJS 2017

### ISSUE THREAD

**Issue by theandersonn** [frontendbr/eventos#162]
**Título**: RSJS 2017
  
**Data**: 08 de Abril de 2017

**Local**: Senac -  Rua Cel. Genuíno, 130 Porto Alegre, Rio Grande do Sul 

**Descrição (breve)**: Sexta edição do mais tradicional evento gaudério de JavaScript do Rio Grande do Sul.

**Logotipo do evento:**:  https://cloud.githubusercontent.com/assets/5203138/22785784/d9a42f3c-eebc-11e6-9522-16f5c269efb1.jpg

**Valor**: Em breve

**Mais informações**: http://rsjs.org/2017/

**Comment by jonathanleal** [comment]
Wooooooooooow, go go go!
