### ISSUE TITLE
[Meetup] Terceiro Vue.js Meetup

### ISSUE THREAD

**Issue by iCaio** [frontendbr/eventos#163]
**Título**: [Meetup] Terceiro Vue.js Meetup
  
**Data**: 16/03

**Local**: Moip Av. Faria Lima, 3064 - 12º andar, São Paulo

**Descrição (breve)**: Terceiro Meetup de Vue.js SP

**Valor**: Free

**Link**: https://www.meetup.com/VueJS-SP/events/237926657/

**Mais informações**:  E é com muita satisfação e alegria nas pernas que anuncio nosso terceiro VueJS SP Meetup. 

O pessoal gente fina do Moip cedeu o espaço para o evento! 

Talks: 

1) Moip talk

2) Igor Luiz: VueJS com GraphQL

3) VueX Live Coding com Vedovelli

**Comment by theandersonn** [comment]
@iCaio Já tem o link pra galera se inscrever por exemplo no meetup.com? Ou não vai rolar inscrição, a galera já chega chegando...?

**Comment by iCaio** [comment]
Esqueci: https://www.meetup.com/VueJS-SP/events/237926657/

**Comment by theandersonn** [comment]
Show! Obrigado por compartilhar com a comunidade! :+1:
