### ISSUE TITLE
[Belo-Horizonte] FrontInBH 2K17

### ISSUE THREAD

**Issue by danielGalvao** [frontendbr/eventos#165]
**Título**: [Belo-Horizonte] FrontInBH 2K17
  
**Data**: 07/10/2017 08h - 18h

**Local**: Rua Diamantina, 463, Lagoinha, Belo horizonte - MG

**Descrição (breve)**: O Front in BH nasceu da necessidade de fortalecer a comunidade Front-end local, através de um circuito de palestras focado em promover o relacionamento e a integração entre os profissionais de Front-end e das áreas a afins.

**Logotipo do evento:**: 
 
**Valor**: 1º Lote - brinde, entrada, coffee: R$90,00

**Mais informações**: http://frontinbh.com.br/

**Comment by theandersonn** [comment]
@danielGalvao Consegue uma versão da logo com outra cor? Branco não dá visibilidade no site.

**Comment by danielGalvao** [comment]
@theandersonn Estou vendo com os organizadores. Valeu!

**Comment by davidsonfellipe** [comment]
@theandersonn @danielGalvao Valeu pessoal, estamos providenciando.

**Comment by davidsonfellipe** [comment]
@theandersonn tem algum tamanho especifico?

**Comment by keppelen** [comment]
@danielGalvao  So o endereço que é melhor deixar vazio, pois ainda não fechamos :)

**Comment by keppelen** [comment]
A logo pode ser essa => https://www.dropbox.com/s/zx6rby1zrrsqd01/logo-sociais.png?dl=0 ou pegar direto em [.ai](https://www.dropbox.com/s/eatas2j7v1h4uju/logo-sociais.ai?dl=0)

**Comment by theandersonn** [comment]
@davidsonfellipe @keppelen  Peguei a logo no link. Até a noite edito essa informação + local. Quando fechar se possivel passe um feedback pra gente que atualizamos.

**Comment by victorferraz** [comment]
@theandersonn geramos uma nova variação usando preto com a logo atualizada.
https://app.box.com/s/cesor4pl8jo9xyyy51dp9vyjbalg6id7

**Comment by theandersonn** [comment]
@victorferraz Show, peguei aqui.

**Comment by keppelen** [comment]
hahha 3 pessoas, 3 links - Adoro comunicação ❤️

**Comment by theandersonn** [comment]
Update na logo e local. Novidades compartilhem conosco. :dancer::dancer::dancer:

**Comment by davidsonfellipe** [comment]
Obrigado pessoal! ❤️

**Comment by danielGalvao** [comment]
@davidsonfellipe @theandersonn @keppelen @victorferraz @renatogalvones  Corrigi a data do evento e adicionei o local! commit 332cf4ec410867fde39addd30

**Comment by victorferraz** [comment]
<3

**Comment by theandersonn** [comment]
@danielGalvao Pode deixar em aberto até a data do evento.
Um comportamento que percebemos aqui no repositório é que alguns visualizam as datas dos eventos pelas issues e outros pelo site; Ficando então duas vias de divulgação.

**Comment by danielGalvao** [comment]
Que irado!
