### ISSUE TITLE
[Recife] Roadsec - 2017

### ISSUE THREAD

**Issue by thulioph** [frontendbr/eventos#166]
**Título**: 
Roadsec - Recife (PE)

**Data**: 
27/05/2017

**Local**: 
*undefined*

**Descrição (breve)**:
Evento sobre hacking, segurança e tecnologia, conta com uma série de palestras e oficinas.

**Logotipo do evento:**: 

**Valor**: 
R$ 40,00 (meia)
R$ 80,00 (inteira)

**Mais informações**:
http://roadsec.com.br/recife2017/

**Comment by theandersonn** [comment]
Pendencia  da localização de onde será realizado o evento.

**Comment by thulioph** [comment]
@theandersonn o site tem **ESSA CIDADE AINDA NÃO TEM LOCAL CONFIRMADO**, será que vale a pena colocar? O que você acha?

**Comment by theandersonn** [comment]
@thulioph Vamos aguardar definirem essas informações, além de não ter local, a grade com palestrantes tbm ainda não está definida (pelo menos no site tbm não consta.)

**Comment by theandersonn** [comment]
@thulioph Add ao site, sabendo novidades compartilhe com a gente.

**Comment by thulioph** [comment]
@theandersonn saiu mais informações:

**Local:**
Faculdade dos Guararapes

**Endereço:**
Rua Comendador José Didier, 27 - Piedade, CEP 54400-160 - Jaboatão dos Guararapes/PE

**Horário**:
9hrs

> http://roadsec.com.br/recife2017/

**Comment by theandersonn** [comment]
@thulioph Show de bola! vou fazer update.
