### ISSUE TITLE
[São Paulo] JS Experience 2017

### ISSUE THREAD

**Issue by theandersonn** [frontendbr/eventos#178]
**Título**: JS Experience
  
**Data**: 22 e 23 de junho

**Local**: Hotel Pullman - Vila Olimpia

**Url map**: https://www.google.com.br/maps/place/Hotel+Pullman+Sao+Paulo+Vila+Olimpia/@-23.5956615,-46.6870368,17z/data=!4m5!3m4!1s0x94ce574f3127b917:0x8be45396adb4f0fc!8m2!3d-23.595893!4d-46.684418

**Descrição (breve)**: O JS Experience 2017 é o primeiro grande evento do iMasters dedicado exclusivamente a Javascript. Serão 2 dias de conteúdo avançado e cerca de 1.000 desenvolvedores para palestras, workshops e diversas ações de networking.

**Logotipo do evento**:  https://cloud.githubusercontent.com/assets/5203138/25748778/b20bf7d0-3182-11e7-9a14-55f722227d21.jpg

**Valor**: A partir de R$ 195,00

**Mais informações**: https://jsexperience2017.imasters.com.br/

**Comment by rubenmarcus** [comment]
o evento parece muito bom, mas nao tem o tema das palestras, queria ir, mas queria saber o que vai ser falado pelos palestrantes tambem.

**Comment by theandersonn** [comment]
@rubenmarcus Acredito que devem disponibilizar a qualquer momento. Envie um email para a organização do evento.
