### ISSUE TITLE
[São Paulo] Quarto VueJS SP Meetup

### ISSUE THREAD

**Issue by icaioincau** [frontendbr/eventos#179]
**Título**: 
  Quarto VueJS SP Meetup

**Data**: 
Quinta-feira, 25 de Maio de 2017

**Local**: 
Moip:Av. Faria Lima, 3064 - 12º andar, São Paulo 

**Descrição (breve)**:
Quarto encontro sobre VueJS rolando aqui em SP, em breve teremos a programação com os temas das palestras.

**Valor**: 
Grátis

**Mais informações**:
https://www.meetup.com/pt-BR/VueJS-SP/events/239813833/

**Comment by theandersonn** [comment]
@icaioincau Já tem um link no meetup ou algo similar?

**Comment by icaioincau** [comment]
Já sim @theandersonn https://www.meetup.com/pt-BR/VueJS-SP/events/239813833/

Esqueci de por, my fault.
