### ISSUE TITLE
[São Paulo] Frontend São Paulo Meetup

### ISSUE THREAD

**Issue by shin-monkey** [frontendbr/eventos#193]
**Título**: Frontend São Paulo Meetup

**Data**: 21/06

**Local**:  Sprinklr - Av. Paulista 2300, 16o Andar

**Descrição (breve)**:Talks sobre SEO, CSS e VueJS!

**Logotipo do evento**: https://image.ibb.co/eDJSsk/FRONTENDSa_o_Paulo_Meetup_2.png

**Valor**: Free

**Mais informações**: 
https://www.meetup.com/Frontend-Dev-SP-Meetup/events/240361660/

**Comment by rubenmarcus** [comment]
estarei lá. pode chegar as 18?

**Comment by shin-monkey** [comment]
Ruben só cabem 60 pessoas lá na Sprinklr. Acredito que pela média dos últimos dois meetups irão umas 50 pessoas. Vai ser por ordem de chegada. Se passar de 60 no próximo eu farei um controle de presença mais rígido. Abraços!
