### ISSUE TITLE
[Porto Alegre] UXConfBR 2016

### ISSUE THREAD

**Issue by diogorodrigues** [frontendbr/eventos#2]
**Título:** UXConfBR 2016

**Data:** 20-21.mai.2016

**Local:** Auditório Master da UniRitter, Porto Alegre

**Descrição:** "Pelo segundo ano, vamos juntar os grandes do Design para a Experiência do Usuário (UXD) em um lugar só."

**Valor:** R$ 300,00 à R$ 550,00

**Mais informações:** http://www.wildtech.com.br/uxconfbr/

**Comment by eduardojmatos** [comment]
Massa! :+1:

**Comment by wstagf** [comment]
Gostaria de saber o preço para os visitantes, e saber possui alguma parceria com hotel para desconto. Somos de Goiânia, talvez uns 4 pessoas.

**Comment by diogorodrigues** [comment]
@wstagf É interessante você entrar em contato com os organizadores do evento. Para isso, [acesse essa página](http://www.eventick.com.br/uxconfbr-2016#) e no final dela você verá um botão para falar com o organizador (está localizado entre o mapa e os comentários). 

Espero que eles consigam te ajudar. Boa sorte! ;D

**Comment by fdaciuk** [comment]
Já foi né?
