### ISSUE TITLE
Privacy error no Chrome

### ISSUE THREAD

**Issue by ribeiroevandro** [frontendbr/eventos#200]
Foi reportado no slack do Training Center que ao tentar acessar o site com `https` o Chrome diz que não é seguro.
![screen shot 2017-07-05 at 4 31 51 pm](https://user-images.githubusercontent.com/943553/27881584-9d6c323e-619f-11e7-8e74-660a0e02f337.png)

**Comment by kvnol** [comment]
@ribeiroevandro aqui está entrando normal para mim, mas nessa última versão do Chrome diversos sites estão mostrando esta mensagem e, ao dar F5, o site carrega normalmente.

**Comment by ribeiroevandro** [comment]
Eu achei que tivessem colocado um Cloudflare por exemplo, sem `https` acessa normal aqui também, mas obrigado pela resposta...

**Comment by leandroaps** [comment]
É por causa do https.
Tira o s, o site roda normal, isso acontece porque não tem SSL nesse
domínio ou existem chamadas de arquivos não seguros não configuradas para
SSL...


-- 

[]´s

*Leandro Ap. de Siqueira*
leandroaps@gmail.com
+55 19 991112239
