### ISSUE TITLE
[Recife] GEEK NIGHT

### ISSUE THREAD

**Issue by talitaoliveira** [frontendbr/eventos#209]
**Título**:  GEEK NIGHT RECIFE
  
**Data**: 27 de julho

**Local**: ThoughtWorks - Recife, PE

**Descrição (breve)**: A Geek Night é um encontro informal mensal onde escolhemos e discutimos sobre um tópico de tecnologia relevante/interessante. Esperamos criar um espaço para discussão de idéias, tecnologias e técnicas no campo do desenvolvimento de software. Pode ser um grupo de pessoas trabalhando em um projeto open source ou trazer seu próprio projeto para trabalharmos.

**Logotipo do evento**: 

**Valor**: Free

**Mais informações**: https://geeknightrecife.github.io

**Comment by WandersonAlves** [comment]
É só chegar @talitaoliveira

**Comment by talitaoliveira** [comment]
tem que se increver pelo sympla. Aqui:
https://www.sympla.com.br/geek-night-recife__169354 @WandersonAlves
