### ISSUE TITLE
[Site] Criação do HTML + CSS básico

### ISSUE THREAD

**Issue by eduardojmatos** [frontendbr/eventos#22]
O @LFeh está tocando a parte de interface básica, como definição de grid, header, footer e container principal.

O branch utilizado é o https://github.com/frontendbr/eventos/tree/interface.

---

OBS: @LFeh se possível, descreva aqui pra gente as escolhas que fez e o que falta pra fecharmos essa issue. Quando for fazer PR do branch `interface` pro `develop`, relaciona também essa issue, please! :heart:

**Comment by LFeh** [comment]
Antes de tudo, os layouts do @diogorodrigues [estão aqui](https://github.com/frontendbr/eventos/tree/layouts)

- [Atomic CSS](https://github.com/frontendbr/forum/issues/89#issuecomment-200359047) para a criação e organização dos componentes. 
- [Mobile First + Rupture](http://www.felipefialho.com/blog/2015/otimizando-e-organizando-as-media-queries/) para organização dos media queries
- [Lost](https://github.com/peterramsing/lost) e Flexbox para os grids (foda-se browsers antigos :p) 
- [Font Magician](https://github.com/jonathantneal/postcss-font-magician/) para os pacotes de fontes

**Comment by LFeh** [comment]
Pessoal, adiantei bastante coisa.

Se alguém conseguir ir criando o sistema para gerar sprites do SVG (e adiciona-los ao layout) agradeço.

Por enquanto está só marcação.

c/c @frontendbr/admins

**Comment by diogomoretti** [comment]
Não sou muito chegado nesse nomenclatura de pastas do AD. Prefiro `components`, `pages`, `helpers`, `base`... Mas tá ficando massa! Vou clonar e ajudar.

**Comment by LFeh** [comment]
Deu algum pau na mensagem do commit.

Mas basicamente 

- Fiz alguns ajustes no banner (adicionei imagem, etc)
- Fiz ajustes de alinhamento
- Adicionei o titulo da sessão e o 'viewer'

Continuo precisando de ajuda para levar o projeto pra frente ;)

**Comment by hevertoncastro** [comment]
Estou dando um estudada no código aqui pra tentar te ajudar @LFeh. Ficou bem legal o topo!

**Comment by LFeh** [comment]
Valeu mano!

**Comment by fdaciuk** [comment]
Tá ficando massa @LFeh, parabéns cara :D 

Só uma dúvida: rola trocar o Jade por [EJS](http://www.embeddedjs.com/) ou [Nunjucks](https://mozilla.github.io/nunjucks/)?

A questão é só pelo motivo de que nós não vamos utilizar HTML, pois o Preact é que vai fazer a renderização da view. Usando uma template engine mais próxima do HTML, fica mais fácil reaproveitar o código que está sendo feito =)

**Comment by LFeh** [comment]
Por mim tranquilo, consegue fazer esse update no que já foi feito até agora?

Dai continuo já na estrutura que você prefere :)

**Comment by fdaciuk** [comment]
@LFeh abri os PRs #30 e #32 ajustando os commits e trocando o template engine para EJS =)
Abri também a issue #31, porque tem uns símbolos que não estão aparecendo, quando puder dar uma olhada :grin:

**Comment by willianjusten** [comment]
@frontendbr/admins 

Pessoal, eu to passando por alguns problemas, então estou diminuindo drasticamente meu tempo de programação. Hoje aceitei os PR, dei uma revisada por alto nas coisas, mas infelizmente não creio que eu vá conseguir trabalhar muito no projeto por agora...

**Comment by LFeh** [comment]
Tranquilo Willian.

Eu ia trabalhar um pouco hoje mas acabou não sobrando tempo, amanhã continuo :)

**Comment by LFeh** [comment]
Pessoal, adicionei o bloco de eventos.

Falta pouco nessa página inicial ;)

**Comment by LFeh** [comment]
Pessoal, fiz coisa pra carario.

- Adicionei o lazyload
- Adicionei  HTMLmin
- Adicionei a paginação
- Adicionei o disclaimer
- Adicionei os icones
- Removi a visualização (não vi necessidade, deixa só lista)

Sendo assim, finalizei a home.

Vocês já podem usar essa estrutura da home para começar a trabalhar nas interações.

Pode dar um feedback @diogorodrigues?

c/c @frontendbr/admins

**Comment by fdaciuk** [comment]
Boa @LFeh!
O HTMLmin provavelmente não vai precisar, porque quando aplicar o Preact a marcação vai ficar por conta do JS, que já vai ser minificado xD

Lazyload, paginação, talvez possa mudar também, pelo mesmo motivo. No mais, show de bola :D 

Acho que é hora de começar a atacar essa parada com JS <3

**Comment by LFeh** [comment]
Paginação foi só interface :p

O lazyload é bem leve, se não tiver problema seria legal manter \o

**Comment by fdaciuk** [comment]
De boa :D 
Sobre o lazyload, não é que vai ser tirado, só tem que ver a compatibilidade pra aplicar junto com o Preact. Mas se não for esse que está, pode ser outro, mas vai ter sim, fica susse =)

**Comment by LFeh** [comment]
@frontendbr/admins 

Pessoal, vocês sabem quando vão começar a parte de desenvolvimento JavaScript no projeto?

**Comment by LFeh** [comment]
Vou começar a fazer a interna.

**Comment by LFeh** [comment]
Pessoal, comecei a fazer a interna

- Fiz o merge das alterações do @zehf para o sprite
- Adicionei o topo 
- Adicionei o conteúdo.

Fica faltando basicamente o bloco de "próximo eventos", se alguém conseguir fazer agradeço profundamente, caso não, só vou retomar esse projeto segunda-feira ;)

c/c @frontendbr/admins 

@diogorodrigues, estou tomando a liberdade de alterar bastante coisa no layout, espero que não se importe. Se possível faz um clone do branch e me passa seu feedback.
