### ISSUE TITLE
[Florianópolis] Front in Floripa

### ISSUE THREAD

**Issue by fdaciuk** [frontendbr/eventos#229]
**Título**: Front in Floripa
  
**Data**: 02 de Dezembro de 2017

**Local**: Hotel Maria do Mar - Florianópolis / SC

**Descrição (breve)**: Esse o ano o Front in Floripa chega em sua 5ª edição. Cada edição são 220 desenvolvedores, designers e entusiastas de toda Santa Catarina e do Brasil reunidos. Esse ano estamos trabalhando em 3 pilares para um ótimo evento.

**Logotipo do evento**: `https://user-images.githubusercontent.com/487669/32276829-92cd4ee8-bef7-11e7-9014-dfaee6d469ff.png`

**Valor**: R$ 80 (primeiro lote)

**Mais informações**: http://frontinfloripa.com.br/

**Comment by fdaciuk** [comment]
@theandersonn adicionei o link do logo :D

**Comment by theandersonn** [comment]
Vou atualizar :)

**Comment by fdaciuk** [comment]
Valeu man :heart:
