### ISSUE TITLE
[Site] Criação do script de render e de leitura do JSON

### ISSUE THREAD

**Issue by eduardojmatos** [frontendbr/eventos#23]
Escolhemos usar o [preact](https://github.com/developit/preact) pra controlar o render de cada evento na listagem e na página de detalhes do mesmo.

Vamos ler um arquivo JSON provisoriamente. Assim que tivermos o CLI pronto, podemos optar em usar uma API ou ainda continuar com o arquivo JSON, mas deixando automatizado a busca de eventos em sites ou facilitando a adição por meio do próprio CLI ou de edição do arquivo.

Mais informações sobre o CLI, na issue #10

**Comment by fdaciuk** [comment]
- Criei toda a base de componentes (menos de paginação, acho que isso dá pra deixar por último);
- Criei uma estrutura inicial para escrever testes com `tape` e `react-dom/server`, para não precisar de browser quando for fazer testes unitários com componentes;
- Deixei o React por enquanto, pois o Preact está com um bug para renderizar SVG sprites;
- Adicionei o travis, para garantir que os PRs estão ok.

---

O que precisa fazer (vou fechar essa issue e criar issues específicas para cada tarefa):
- Aplicar Redux para os eventos;
- Usar ajax para buscar o json (ao fazer o build, ele é exportado em `/build/data/events.json`): https://github.com/frontendbr/eventos/blob/develop/src/data/events.json;
- Escrever testes para o reducer de eventos (garantir que os dados adicionados no JSON são suficientes para cadastrar um evento);
- Fazer funcionar busca;
- Fazer funcionar filtros dos selects;
- Fazer funcionar paginação.

Acho que é isso xD

**Comment by fdaciuk** [comment]
Criei todas as tarefas, e tageei com `Site`. Acho que dá pra fechar essa. Se precisar abrir novamente, fiquem à vontade =)

cc/ @frontendbr/admins
