### ISSUE TITLE
Meetup React SP #15 - Especial São Paulo Tech Week

### ISSUE THREAD

**Issue by danvitoriano** [frontendbr/eventos#232]
**Título**: Meetup React SP 15 especial São Paulo Tech Week
  
**Data**: 9/11/2017

**Local**: [Webforce Coworking - Av. República do Líbado, 331 Ibirapuera São Paulo SP](https://www.google.com.br/maps/place/Webforce+Networks/@-23.583261,-46.6632055,15z/data=!4m5!3m4!1s0x0:0x10b3d5e260af490e!8m2!3d-23.583261!4d-46.6632055)

**Descrição (breve)**: Nosso encontro #15 será uma edição especial para a São Paulo Tech Week com duas talks: O Eduardo Shin do Meetup Frontend SP e da Monkey Exchange falando de MobX e o Luiz Camargo da Entria falando sobre Flexbox no React Native. O encontro será na Webforce Coworking, totalmente integrado ao Parque do Ibirapuera! Teremos a presença de Food Trucks vendendo hamburguers, doces e bebidas.

**Logotipo do evento**: `https://drive.google.com/file/d/0Bxl-8_oWXUXXOC1QRDhiblRfczA/view?usp=sharing`

https://user-images.githubusercontent.com/5203138/32324827-cc244e64-bfb3-11e7-8e8f-75a54aad83d1.png

**Valor**: Gratuito

**Mais informações**: Inscrições [Meetup React SP](https://www.meetup.com/pt-BR/ReactJS-SP/events/244724543/)

**Comment by thiagoah** [comment]
Em sáb, 11 de nov de 2017 às 10:53, Anderson Nascimento <
notifications@github.com> escreveu:
