### ISSUE TITLE
[São Paulo] - #7 Frontend SP Meetup

### ISSUE THREAD

**Issue by shin-monkey** [frontendbr/eventos#235]
**Título**: #7 Frontend São Paulo Meetup
  
**Data**: 16/11/2017

**Local**: iMasters - Rua Oscar Freire, 2379 - Pinheiros, São Paulo - SP

**Descrição (breve)**: Palestras e discussões sobre Data Science e Vue vs React!

**Url Map**: https://www.google.com.br/maps/place/iMasters/@-23.5523916,-46.6778991,15z/data=!4m2!3m1!1s0x0:0xbe87cea048990b91?sa=X&ved=0ahUKEwikp7z5vqrXAhWFYyYKHcvlDowQ_BIIeDAN

**Logotipo do evento**: https://image.ibb.co/eDJSsk/FRONTENDSa_o_Paulo_Meetup_2.png

**Valor**: De grátis (Traga refri / suco / salgadinho pro coffee!)

**Mais informações**: https://www.meetup.com/Frontend-Dev-SP-Meetup/events/244561510/

**Comment by shin-monkey** [comment]
Pessoal, eu corrigi a descrição que estava errada, peço desculpas.

**Comment by theandersonn** [comment]
@shin-monkey Beleza, vou atualizar :+1:
