### ISSUE TITLE
[Florianópolis] - 17º Meetup WordPress Floripa

### ISSUE THREAD

**Issue by lciceris** [frontendbr/eventos#248]
**Título**: 17º Meetup WordPress Floripa
  
**Data**: 03/03/2018

**Local**: [Mansão da InCuca - Servidão Aroeiras do Gramal, nº 250, Campeche, Florianópolis](https://www.google.com/maps/place/Servid%C3%A3o+Aroeiras+do+Gramal,+250+-+Campeche,+Florian%C3%B3polis+-+SC,+88063-230/@-27.6942078,-48.4953942,17z/data=!4m5!3m4!1s0x95273b40c20dffc9:0xd866f1eb79e243ba!8m2!3d-27.6917474!4d-48.4955551?hl=en)

**Descrição (breve)**: 
Neste meetup Lucas Adiers Stefanello iniciará com a talk Qual a importância de formar uma comunidade exponencial e colaborativa. Em seguida faremos o famoso jogo de perguntas e respostas onde cada participante pode escrever suas dúvidas, curiosidades, assuntos sobre WordPress para os participantes responderem. Vamos continuar as definições e criações dos preparativos para o WordCamp Floripa 2018, que será realizado dia 07/04 no SENAC no Centro de Florianópolis. Teremos Coffee-break!!!

**Logotipo do evento**: https://secure.meetupstatic.com/photos/event/5/b/e/2/highres_453863522.jpeg

**Valor**: Gratuito

**Mais informações**: [Meetup WordPress Floripa](https://www.meetup.com/pt-BR/Meetup-Wordpress-Floripa/events/247344194/)

**Comment by theandersonn** [comment]
@lciceris É possivel preparar uma descrição enxuta para colocarmos no site de eventos?

**Comment by lciceris** [comment]
@theandersonn deixei ela mais enxuta agora, ta de boas assim ou precisa diminuir mais ?

**Comment by theandersonn** [comment]
É interessante descrição corrida, olhe só como fica online
http://frontendbr.com.br/eventos/

Tipo 3,4 linhas.

Mais ou menos assim... o que acha?

Neste meetup Lucas Adiers Stefanello iniciará com a talk Qual a importância de formar uma comunidade exponencial e colaborativa. Em seguida faremos o famoso jogo de perguntas e respostas onde cada participante pode escrever suas dúvidas, curiosidades, assuntos sobre WordPress para os participantes responderem. Vamos continuar as definições e criações dos preparativos para o WordCamp Floripa 2018, que será realizado dia 07/04 no SENAC no Centro de Florianópolis. Teremos Coffee-break!!!

**Comment by lciceris** [comment]
Perfeito mano, vou atualizar aqui e nos próximos posto seguindo esse padrão já, valeuzão (:

**Comment by theandersonn** [comment]
Show! O evento está add no site.
Quando tiver tudo certo pro WordCamp compartilhe com a gente!
