### ISSUE TITLE
[Campinas] Front in Campinas

### ISSUE THREAD

**Issue by theandersonn** [frontendbr/eventos#250]
**Título**: Front in Campinas 2018
  
**Data**: 12 de maio de 2018

**Local**: Vitória Hotel Concept Campinas  

**URL Map**: https://www.google.com.br/maps/place/VIT%C3%93RIA+HOTEL+CONCEPT+CAMPINAS/@-22.9024731,-47.0501841,17z/data=!3m1!4b1!4m5!3m4!1s0x94c8cf463aa8d455:0x17bc5c6b4ce7c6ff!8m2!3d-22.9024731!4d-47.0479954

**Descrição (breve)**: Primeira edição de um evento 100% focado em front-end na cidade de Campinas. Será um dia todo com conteúdos de alta qualidade, diversão e muito networking.

**Logotipo do evento**: https://user-images.githubusercontent.com/5203138/36631265-a23b83e8-1953-11e8-9068-ce9365427097.png

**Valor**: A partir de R$90,00

**Call 4 Papers**: https://docs.google.com/forms/d/e/1FAIpQLSdYzQBbJj7sNHCV5vAKFjWpZVKC084htDIAt5dtm0QZha4Umg/viewform

**Mais informações**: http://frontincampinas.com.br

**Comment by marcocoelho** [comment]
Já tem os palestrante e temas definidos?

**Comment by theandersonn** [comment]
@marcocoelho Acredito que ainda não, está rolando Call 4 Papers.
De qualquer forma, recomento consultar a staff:
http://frontincampinas.com.br/

**Comment by luisfmsouza** [comment]
Opa @marcocoelho ! 

Ainda não temos nenhum palestrante definido, mas teremos surpresas boas nos próximos dias :)

Fica de olho no site e/ou twitter [@cpsfrontend](https://twitter.com/cpsfrontend) que vamos divulgar por lá.
