### ISSUE TITLE
[Porto Alegre] BrazilJS 2018

### ISSUE THREAD

**Issue by theandersonn** [frontendbr/eventos#251]
**Título**: BrazilJS 2018  
  
**Data**: 24 e 25 de agosto

**Local**: Barra Shopping Sul

**Descrição (breve)**: A já tradicional e querida BrazilJS Conf, maior conferência JavaScript do mundo, está com os dias de sua sétima edição confirmados: 24 e 25 de Agosto, no Barra Shopping Sul, na zona Sul de Porto Alegre.

**Logotipo do evento**: 

**Valor**: A partir de R$ 124,90 (para estudantes)

**Mais informações**: https://braziljs.org/conf/

**Comment by renanbastos93** [comment]
@theandersonn vale a pena informar que os 124 reais, são para estudantes. Se não parece que esse ingresso é para todos o valor.

**Comment by theandersonn** [comment]
Sim @renanbastos93 é uma boa, obrigado pela sugestão.

**Comment by renanbastos93** [comment]
De nada!
