### ISSUE TITLE
[Florianópolis] WordCamp Floripa 2018

### ISSUE THREAD

**Issue by theandersonn** [frontendbr/eventos#252]
**Título**: WordCamp Floripa 2018
  
**Data**: 07 de abril

**Local**: Senac - Centro

**Descrição (breve)**: O WordCamp é a conferência anual de WordPress que se originou nos Estados Unidos. Em Florianópolis esta será a 1ª edição do evento, contando com um dia de workshops, palestras e muita troca de conhecimento sobre a plataforma de criação de sites mais utilizada da atualidade.

**Logotipo do evento**:  https://2018.floripa.wordcamp.org/files/2018/02/logo-home.png

**Valor**: R$ 60,00

**Mais informações**: https://2018.floripa.wordcamp.org/

**Comment by lciceris** [comment]
@theandersonn saiu o valor do ingresso, 60 reais. Também já abrimos as [vendas dos ingressos](https://2018.floripa.wordcamp.org/tickets/). Consegue alterar isso por favor ?

**Comment by theandersonn** [comment]
@lciceris Com certeza, troco sim :)

**Comment by lciceris** [comment]
@theandersonn valeuzão (:
