### ISSUE TITLE
[Rio de Janeiro] JSDay 2018

### ISSUE THREAD

**Issue by Lucasktrindade** [frontendbr/eventos#255]
**Título**:  JSDay Rio de Janeiro
  
**Data**: 9 de Junho de 2018

**Local**:  Nave Cidade Olímpica - Rua Arquias Cordeiro, 1516, Engenho de Dentro, Rio de Janeiro

**Descrição (breve)**: O JSDay Brasil foi criado para trazer temas atuais e inovadores sobre a linguagem mais utilizada do mundo, o JavaScript!

**Logotipo do evento**: https://d1gkntzr8mxq7s.cloudfront.net/5abafdcf09a25-lg.jpg

**Valor**:  Gratuito 

**Mais informações**: Inscrições no [Sympla](https://www.sympla.com.br/jsday-rio-de-janeiro-2018__261190) e [Call4Papers](https://goo.gl/forms/QJa2cN9eRzo5wBh03), outras informações é possível encontrar em nosso site [JSDay Rio](rio.jsday.com.br).

**Comment by Lucasktrindade** [comment]
Opa, é possível alterar o Local no JSON? Tivemos um problema e trocamos o local.

Novo Local: Oito Coworking - AV. VISCONDE DE PIRAJÁ, 54, Ipanema, Rio de Janeiro

**Comment by theandersonn** [comment]
@Lucasktrindade Update feito.
