### ISSUE TITLE
[Porto Alegre] RSJS 2018

### ISSUE THREAD

**Issue by theandersonn** [frontendbr/eventos#258]
**Título**: RSJS 2018
  
**Data**: 30 de Junho

**Local**: Senac

**Map**: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3454.0545657490948!2d-51.22860358488512!3d-30.035292381885625!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95197906acdae77f%3A0x3c15bb6b7754488e!2sR.+Cel.+Genu%C3%ADno%2C+130+-+Centro+Hist%C3%B3rico%2C+Porto+Alegre+-+RS!5e0!3m2!1spt-BR!2sbr!4v1528769114668

**Descrição (breve)**: Sétima edição do mais tradicional evento gaudério de JavaScript do Rio Grande do Sul.

**Logotipo do evento**: https://event-kraken.s3.amazonaws.com/event/posters/24229/medium.jpg

**Valor**: A partir de R$99,00 (meia) 

**Mais informações**: https://braziljs.org/eventos/rsjs-2018/

**Comment by mikaelhadler** [comment]
Closed? :+1: Já rolou

**Comment by mikaelhadler** [comment]
@renanbastos93 foi uma afirmação! Haha, também estava lá :+1:

**Comment by theandersonn** [comment]
@mikaelhadler Vou remover. Obrigado pelo Feedback.
