### ISSUE TITLE
[Site] Busca

### ISSUE THREAD

**Issue by eduardojmatos** [frontendbr/eventos#26]
Mais uma vez, usando nosso querido [preact](https://github.com/developit/preact), teremos que criar um script que faça uma busca nos eventos através de palavra-chave digitada.

Sugiro começarmos simples, com busca levando em conta o título e local do evento. Data e outras informações, acredito que podemos deixar pra um segundo momento.

**Comment by fdaciuk** [comment]
Estou fazendo na #51  =)

**Comment by fdaciuk** [comment]
Done!
