### ISSUE TITLE
[Rio de Janeiro] Coders In Rio Summit 2018

### ISSUE THREAD

**Issue by eduardoflorence** [frontendbr/eventos#261]
**Título**: Coders In Rio Summit
  
**Data**: 10 de Novembro de 2018

**Local**: Senac RJ - Flamengo

**Map**: https://goo.gl/maps/Q7jo8CLDbuD2

**Descrição (breve)**: O CODERS IN RIO SUMMIT foi criado pelos maiores influenciadores de comunidades técnicas do Rio de Janeiro com o objetivo de reunir todas as pessoas que tem paixão pelo conhecimento. Venha prestigiar e aprender com conteúdo altamente selecionado e prepare-se para agregar valor ao seu conhecimento profissional e fazer muito networking. Serão mais de 8 horas de imersão nas tecnologias mais faladas no momento com os maiores nomes da comunidade técnica do Brasil.

**Logotipo do evento**:  https://codersinrio.com.br/wp-content/uploads/2018/06/logosite-1.png

**Valor**: A partir de R$150,00 (lote 1)

**Mais informações**: https://codersinrio.com.br/

**Comment by JLammeer** [comment]
Vai ter algum tipo de transmissão do evento?

**Comment by efc30** [comment]
Não, evento somente presencial.
