### ISSUE TITLE
[Maringá] FEMUG MGA #16 - Universidade Estadual de Maringá

### ISSUE THREAD

**Issue by juliovedovatto** [frontendbr/eventos#263]
**Título**:  FEMUG Maringá 16

**Data**:  29 de Setembro de 2018

**Local**: Universidade Estadual de Maringá - Bloco C56

**Descrição (breve)**:

No mês de Setembro, estaremos com mais uma edição do Encontro de Frontend, aqui em Maringá.

Este FEMUG terá muito conhecimento e networking! Pedimos que confirmem sua presença no link acima.

**Logotipo do evento**: https://drive.google.com/uc?export=view&id=143XR-yCOjPkH2cE3jeWm554gvvMF15qK

![femug](https://user-images.githubusercontent.com/5203138/45269184-f760a900-b45f-11e8-9ace-b7d5537088c2.png)

**Valor**: Gratuito

**Mais informações**: 

Confirmar participação em nossa página do meetup https://goo.gl/6mpJNR

Call for Papers (disponível até 21/09): https://goo.gl/XatXfG

**Comment by JLammeer** [comment]
Vai ter transmissão ao vivo?

**Comment by juliovedovatto** [comment]
@JLammeer não posso lhe dar certeza. Temos muita dificuldade com transmissão ao vivo, questões de logística e qualidade de conexão onde fazemos os meetups :(

**Comment by renanbastos93** [comment]
@juliovedovatto, sugiro realizar a gravação aí depois colocar no youtube. Que acha?
