### ISSUE TITLE
[Fortaleza] CEJS 2018

### ISSUE THREAD

**Issue by victornery** [frontendbr/eventos#265]
**Título**: CEJS 2018
  
**Data**: 06/10/2018

**Local**: Universidade 7 de Setembro (UNI7) - Av. Alm. Maximiano da Fonseca, 1395 - Eng. Luciano Cavalcante - Fortaleza/CE

**Descrição (breve)**: Mais uma Conferência de JavaScript em Fortaleza, capital do Ceará, com grandes representantes do Front-end no Brasil.

**Logotipo do evento**: http://www.cejs.com.br/images/logo-yellow-small.png

**Valor**: R$120 (4º lote)

**Mais informações**: 

Link do Evento: [http://www.cejs.com.br/](http://www.cejs.com.br/)

**Comment by JLammeer** [comment]
Vai ter transmissão online?

**Comment by victornery** [comment]
> Vai ter transmissão online?

Vou me informar com a organização do evento e, caso não, sugerir-vos.

Obrigado pela sugestão.
