### ISSUE TITLE
[Fortaleza] 1º Meetup Front-end CE

### ISSUE THREAD

**Issue by felipepatricio** [frontendbr/eventos#279]
**Título**: 1º Meetup Front-end CE

**Data**: 24 de Novembro

**Local**: GreenMile

**Descrição (breve)**: Nós somos uma comunidade fundada com o princípio de levar a tecnologia como fator de mudança na vida de muitas pessoas, unir a comunidade, se conhecer e fazer com que o Ceará se consolide como um das maiores e melhores polos de Desenvolvimento Front-end no Brasil. Essa é a primeira rodada de meetups da comunidade.

**Logotipo do evento**:

**Valor**: 1 KG de Alimento Não perecível

**Mais informações**: https://frontendce.com.br

**Transmissão ao vivo**: https://www.instagram.com/frontendce/

**O conteúdo será gravado**: Não

**Comment by theandersonn** [comment]
@felipepatricio Iniciativa espetacular, parabéns pelo empenho e sucesso!

**Comment by felipepatricio** [comment]
> @felipepatricio Iniciativa espetacular, parabéns pelo empenho e sucesso!

Obrigado @theandersonn

**Comment by theandersonn** [comment]
@felipepatricio O link https://frontendce.com.br não está abrindo.

**Comment by felipepatricio** [comment]
> @felipepatricio O link https://frontendce.com.br não está abrindo.

Esse link só redireciona para o link do meetup, por enquanto concluo o site. Testei agora e funcionou.

**Comment by theandersonn** [comment]
Testei agora e por aqui ainda não funciona. Pode ser cache/dns etc... de qualquer forma coloquei o link direto para o meetup.

**Comment by felipepatricio** [comment]
vai ser no instagram da comunidade @frontendce https://www.instagram.com/frontendce/

**Comment by theandersonn** [comment]
Beleza! Fiz update na logo. Na descrição aqui da issue editei e coloquei o link da transmissão, mas no front-end do site ainda precisamos implementar essa inclusão.

**Comment by felipepatricio** [comment]
Tranquilo cara. Obrigado.

**Comment by JLammeer** [comment]
Vou assistir pelo Insta, já que moro longe.

**Comment by felipepatricio** [comment]
> Vou assistir pelo Insta, já que moro longe. Que horas começa?

Você mora onde ?

**Comment by JLammeer** [comment]
@felipepatricio Moro em Pernambuco, 👍 .
