### ISSUE TITLE
[Maceió] CSSday

### ISSUE THREAD

**Issue by theandersonn** [frontendbr/eventos#28]
**Título**: CSSday Maceió 2016
  
**Data**: 07 de maio

**Local**: Auditório João Sampaio

**Descrição (breve)**: Um dia imersivo para que possamos reconhecer a importância do CSS no cenário do Desenvolvimento Web

**Valor**: A partir de R$35,00

**Mais informações**: http://cssday.com.br/

**Comment by LFeh** [comment]
Muito foda

**Comment by fdaciuk** [comment]
Já foi?
