### ISSUE TITLE
[Rio de Janeiro/Online] Dicas & Truques do VS Code para Desenvolvedores JavaScript by Loiane Groner

### ISSUE THREAD

**Issue by glaucia86** [frontendbr/eventos#282]
**Título**: WEBINAR: Dicas & Truques do VS Code para Desenvolvedores JavaScript by Loiane Groner
  
**Data**: 20/11/2018 às 21h

**Local**: Online

**Descrição (breve)**:

Super Webinar no meu canal no próximo dia 20/11 com uma das maiores desenvolvedoras da atualidade: Loiane Gronner.
Loiane estará dando dicas e truques fundamentais para todos desenvolvedores Javascript que fazem uso do VS Code. 
Durante o Webinar, Loaine nos mostrará configurações e extensões do VS Code que ajudam a aumentar a produtividade em seus trabalho.
Após o webinar, estaremos batendo papo (open mic) para falar sobre a sua carreira e entre outros temas. 

Venham assistir!!

**Logotipo do evento**: ![alt text](https://i.imgsafe.org/ed/ed460cec88.jpeg)

**Valor**: Grátis

**Mais informações**:  Ao final do Webinar estaremos fazendo um open mic, com intuito de todos poderem participar e fazer perguntas para a Loaine Groner

**Transmissão ao vivo**: Sim **[LINK TRANSMISSÃO](https://bit.ly/2Bc1uB7)**

**O conteúdo será gravado**: Sim

**Comment by JLammeer** [comment]
Vou assistir, sim!

Também gostaria de saber se o horário segue o de Brasília e se o chat poderá fazer perguntas.
