### ISSUE TITLE
[Porto Alegre] PHP Conference Brasil

### ISSUE THREAD

**Issue by rhcarlosweb** [frontendbr/eventos#283]
**Título**: PHP Conference Brasil
  
**Data**: 6 a 8 de Dezembro 2018

**Local**: Faculdade SENAC - Porto Alegre (RS)

**Descrição (breve)**:
O Principal evento de PHP da América Latina

**Logotipo do evento**: 
<img src="https://phpconference.com.br/wp-content/uploads/2018/03/PHP-Conference-Brasil-Logo-W-S-100px.png">

**Valor**: 
- Silver: Inclui todas as palestras
- Gold: Inclui todas as palestras e um Curso Mão-na-Massa de 8 horas que será escolhido com antecedência e oportunamente a partir do LOTE 1.

~~Lote - 1 Até 14 de Setembro  [Encerrado]~~

**Lote 2 - Até 30 de Novembro**
**Clientes**:
Silver: R$199,00
Gold: R$349,00 

**Não-Clientes**:
Silver: R$249,00
Gold: R$399,00 

**Lote 3 - Até 4 de Dezembro**
**Clientes**:
Silver: R$249,00
Gold: R$399,00 

**Não-Clientes**:
Silver: R$299,00
Gold: R$449,00 

**Mais informações**: 
https://phpconference.com.br

**Transmissão ao vivo**:
Não informado

**O conteúdo será gravado**:
Não informado

**Comment by theandersonn** [comment]
@frontendbr/admins Podemos incluir em nossa listagem eventos Back-End?

**Minha opinião:** Quanto mais global, melhor. Ainda mais o PHP tão presente em nossas rotinas.

**Comment by rhcarlosweb** [comment]
Acredito que sim @theandersonn eu só queria compartilhar o evento porque ainda não tinha aqui, e acho que quanto mais melhor haha

**Comment by theandersonn** [comment]
@rhcarlosweb Aqui mesmo, a questão é que esse é o primeiro evento backend que recebemos. Por mim, blz... como falei acima. Aguardar um pouquinho a opinião do grupo que auxilia na administração.

**Comment by fdaciuk** [comment]
Opa, eae pessoas =)
Não vejo problemas adicionar alguns eventos de backend, desde que nesses eventos tenha algum conteúdo relacionado também a frontend.

A ideia desse repo é manter apenas eventos de frontend mesmo, até pra facilitar a busca das pessoas que são da área e querem participar de eventos para frontenders.

Mas @rhcarlosweb, você pode postar esse evento também no repositório de eventos do backend-br, que é um fork desse repo:
https://github.com/backend-br/eventos

Acho que assim fica mais organizado =)

**Comment by eduardojmatos** [comment]
Olá pessoal! Compartilho da mesma ideia do @fdaciuk. O repositório https://github.com/backend-br/eventos é exatamente pra eventos, como esse de PHP!

Se colocarmos de PHP ou de outra linguagem não relacionada com front-end vamos confundir a galera que entra no repo procurando vagas :/

**Comment by LFeh** [comment]
Acho que pode ter eventos com pegada mais back desde que tenha assuntos front incluídos.

Eventos de Node, por exemplo, se encaixariam nesse propósito 😊

**Comment by Mendrone** [comment]
Concordo com vocês! Se o evento abordar, por exemplo, Wordpress ou Laravel, já acho válido ser listado porque são ferramentas bem comuns no dia a dia de muitos devs front-end

**Comment by rhcarlosweb** [comment]
> Olá pessoal! Compartilho da mesma ideia do @fdaciuk. O repositório https://github.com/backend-br/eventos é exatamente pra eventos, como esse de PHP!
> 
> Se colocarmos de PHP ou de outra linguagem não relacionada com front-end vamos confundir a galera que entra no repo procurando vagas :/

Valeu, não conhecia esse repo
