### ISSUE TITLE
[São Paulo] Front In Sampa

### ISSUE THREAD

**Issue by keitoliveira** [frontendbr/eventos#290]
**Título**: Front In Sampa 2019
  
**Data**: 13/07/2019

**Local**: Auditório Centro de Convenções Rebouças - Avenida Rebouças, 600, Pinheiros, São Paulo, SP, 05402-000

**Descrição (breve)**: A 8º e maior edição do mais **tradicional evento de Front-end** do Brasil. Aprendizado, diversão e compartilhamento. Líderes, influenciadores e empresas da área reunidos na maior cidade da América Latina para 8 horas de conteúdo de tecnologia e software.

**Logotipo do evento**: https://www.frontinsampa.com.br/assets/logo.svg

**Valor**: De R$ 80,00 à R$350,00

**Mais informações**: 

**Transmissão ao vivo**: 

**O conteúdo será gravado**: Sim

**Link**: https://www.frontinsampa.com.br

**Comment by phsantiago** [comment]
Já teve call for papers?

**Comment by keitoliveira** [comment]
Ainda não mas fique de olho 🚀🔥
