### ISSUE TITLE
[Porto Alegre] BrazilJS 2019

### ISSUE THREAD

**Issue by theandersonn** [frontendbr/eventos#302]
**Título**:  BrazilJS Conf 2019
  
**Data**:  23 e 24 de agosto

**Local**: Barra Shopping Sul

**Descrição (breve)**: A BrazilJS Conf chega em sua 9ª edição. O evento acontecerá nos dias 23 e 24 de Agosto, em Porto Alegre, no Barra Shopping Sul.

**Logotipo do evento**: https://braziljs.org/wp-content/uploads/2019/04/15_Logotipo-2.png

**Valor**: Acessar site

**Mais informações**: https://braziljs.org/eventos/braziljs-conf/2019/

**Transmissão ao vivo**: Não informado

**O conteúdo será gravado**: Sim

**Comment by kaueDM** [comment]
@theandersonn qual é o horário de início e fim?

**Comment by theandersonn** [comment]
@kaueDM Ainda não divulgaram a grade completa e horários... mas começaram a divulgar os primeiros palestrantes.
https://braziljs.org/eventos/braziljs-conf/2019/
