### ISSUE TITLE
[Maringá] Front In Maringá

### ISSUE THREAD

**Issue by iamgbayer** [frontendbr/eventos#309]
**Título**: Front In Maringá

**Data**: 14/09/2019

**Local**: SEBRAE Maringá

**Descrição (breve)**: Vem aí a **edição 2019 do Front In Maringá**, uma dia inteiro de muito networking e imersão no ecossistema frontend com diversas pessoas que são referências trazendo conteúdo de muita qualidade.

**Logotipo do evento**: https://user-images.githubusercontent.com/5203138/60722252-b8c43f80-9f06-11e9-8105-3f0142ae48f3.jpg

**Valor**: A partir de R$44,00

**Mais informações**:
[facebook.com/frontinmga](https://facebook.com/frontinmga)
[twitter.com/frontinmga](https://twitter.com/frontinmga)
[frontin.maringa.br](https://frontin.maringa.br)

**Transmissão ao vivo**: Não

**O conteúdo será gravado**: Não

**Comment by theandersonn** [comment]
Alterei a logo porque a url com versão svg não abriu.
