### ISSUE TITLE
Imagens no site

### ISSUE THREAD

**Issue by fdaciuk** [frontendbr/eventos#31]
@LFeh o que era pra ser esses símbolos? Não rola colocar como SVG? Ou eu que estou fazendo alguma besteira que não está aparecendo direito pra mim?

![selection_182](https://cloud.githubusercontent.com/assets/487669/14401344/2bb60c10-fde5-11e5-93cb-f077c4b8615b.png)

---

![selection_183](https://cloud.githubusercontent.com/assets/487669/14401345/2d6eaa8a-fde5-11e5-8c1d-0b9cf01ecb4f.png)

**Comment by LFeh** [comment]
Hahaha, não se preocupa. É só marcação. Ainda vou colocar os ícones :)

**Comment by fdaciuk** [comment]
Show então :D
