### ISSUE TITLE
Trocar template engine de Jade para EJS

### ISSUE THREAD

**Issue by fdaciuk** [frontendbr/eventos#32]
- [x] Remover `gulp-jade`;
- [x] Adicionar `gulp-ejs`;
- [x] Substituir caminhos dos arquivos do `jade` para o `ejs`;
- [x] Adicionar task `ejs` no lugar do `jade`;
- [x] Adicionar NPM scripts para não depender do `gulp` global;
- [x] Atualizar README, tirando Jade e adicionando EJS;
- [x] Atualizar README com os NPM scripts necessários para rodar o projeto;

> #33

**Comment by willianjusten** [comment]
Feito e mergeado =)
