### ISSUE TITLE
  CEJS 2019

### ISSUE THREAD

**Issue by ti4luciano** [frontendbr/eventos#320]
**Título**: 
  CEJS 2019
**Data**: 
05 de outubro de 2019, 09h-18h 
**Local**: 
UNI7 - Fortaleza, CE
**Descrição (breve)**:
Disseminar tecnologias web com foco na linguagem JavaScript e suas ferramentas.
**Logotipo do evento**: 
Não Informado
**Valor**: 
Ver link abaixo
**Mais informações**: 
https://www.sympla.com.br/cejs-2019__564280
**Transmissão ao vivo**:
Não informado
**O conteúdo será gravado**:
Não informado

**Comment by theandersonn** [comment]
@ti4luciano que show! Obrigado pela contribuição.
Mas foi add aqui:
https://github.com/frontendbr/eventos/issues/315

**Comment by ti4luciano** [comment]
@theandersonn desculpa pela desatenção acabou passando desapercebido e obrigado pela pronta correção. :smile:

**Comment by theandersonn** [comment]
Imagina! Fique a vontade em contribuir!
