### ISSUE TITLE
BrazilJS OnTheRoad Fortaleza

### ISSUE THREAD

**Issue by theandersonn** [frontendbr/eventos#326]
**Título**: BrazilJS OnTheRoad Fortaleza
  
**Data**: 21 de março de 2020

**Local**: Centro Universitário 7 de Setembro

**URL Map**: https://goo.gl/maps/7XPMJFCjzjGTECip9

**Descrição (breve)**: A história da BrazilJS inicia em Fortaleza, em 2011, com a primeira edição da BrazilJS Conf. Em 2017 voltamos com uma edição dupla, acontecendo em uma semana em Porto Alegre e na outra em Fortaleza. Em 2020 estamos de volta, dessa vez trazendo o projeto BrazilJS on the road.

**Logotipo do evento**: 

**Valor**: Consultar

**Mais informações**: https://braziljs.org/eventos/otr-fortaleza/2020

**Transmissão ao vivo**: Não Informado 

**O conteúdo será gravado**: Não Informado

**Comment by thebylito** [comment]
Boa tarde, temos interesse em participar. Somos 6 devs, da empresa Goowit. Há alguma forma de de obter descontos?  :)
