### ISSUE TITLE
BrazilJS OnTheRoad Belem

### ISSUE THREAD

**Issue by theandersonn** [frontendbr/eventos#330]
**Título**: BrazilJS OnTheRoad Belem
  
**Data**: 08 de agosto de 2020 

**Local**: Auditório David Mufarrej - Unama Alcindo Cacela

**URL Map**: https://goo.gl/maps/mPTbDsF9igHLjFWV9

**Descrição (breve)**: Pela primeira vez a BrazilJS chega a Belém!

**Logotipo do evento**: 

**Valor**: Consultar

**Mais informações**: https://braziljs.org/eventos/otr-belem/2020

**Transmissão ao vivo**: Não informado

**O conteúdo será gravado**: Sim

**Comment by thauska** [comment]
Conteúdo será gravado

**Comment by theandersonn** [comment]
@thauska Obrigado pelo feedback.
