### ISSUE TITLE
JS+ TechTalks #3 - GraphQL + Serverless

### ISSUE THREAD

**Issue by felipefialho** [frontendbr/eventos#348]
**Título**: `JS+ TechTalks #3 - GraphQL + Serverless`
  
**Data**: 25 de junho de 2020, 19h30-21h

**Local**: https://www.sympla.com.br/js-techtalks-3---graphql--serverless__876234

**Url no Google Maps**: N/A

**Descrição (breve)**: Nessa talk construiremos APIs utilizando GraphQL em uma arquitetura Serverless.

**Logotipo do evento**: 

![image](https://user-images.githubusercontent.com/3603793/85302276-551c8480-b47f-11ea-9922-a53ff5c55260.png)

**Valor**: R$ 0.00

**Mais informações**: https://www.sympla.com.br/js-techtalks-3---graphql--serverless__876234

**Transmissão ao vivo**: https://www.sympla.com.br/js-techtalks-3---graphql--serverless__876234

**O conteúdo será gravado**: Sim

**Comment by MrS4w** [comment]
25 de junho, vai ser meu presente de aniversário? 😅 
O @muriloamendola manda muito!
