### ISSUE TITLE
[Fortaleza] 4º Meetup ReactJS Ceará

### ISSUE THREAD

**Issue by theandersonn** [frontendbr/eventos#359]
**Título**: [Fortaleza] 4º Meetup ReactJS Ceará
  
**Data**: 25 de junho de 2022, 09h-12h

**Local**: Av. Santos Dumont, 1510 - Fortaleza, CE

**Url no Google Maps**: https://www.google.com/maps/place/Av.+Santos+Dumont,+1510+-+Aldeota,+Fortaleza+-+CE,+60150-161/@-3.7327595,-38.5105737,17z/data=!3m1!4b1!4m5!3m4!1s0x7c7485edb2a6f1d:0x914ca3ab641fbf93!8m2!3d-3.7327595!4d-38.5105737

**Descrição (breve)**: No dia 25 de junho a patir das 9h, estaremos novamente na Digital College realizando o 4º meetup (presencial).

**Logotipo do evento**: 

**Valor**: Em breve

**Mais informações**: https://linktr.ee/react.js.ceara

**Transmissão ao vivo**: Não informado

**O conteúdo será gravado**: Não informado

**Comment by felipefialho** [comment]
Bom ver os eventos presenciais voltando a acontecer 😁

**Comment by theandersonn** [comment]
Emocionante!!!!
