### ISSUE TITLE
[São Paulo] FrontUX #11

### ISSUE THREAD

**Issue by matmarsiglio** [frontendbr/eventos#37]
**Título**:  FrontUX Edição 11 na Fastcommerce
  
**Data**: 28/04/2016

**Local**: Av. Rouxinol, 1041

**Descrição (breve)**: O encontro tem o objetivo de promover a troca de conhecimento entre designers e desenvolvedores, aproximar os dois mundos e melhorar o fluxo de trabalho dos profissionais de cada área, possibilitando que designers opinem sobre tecnologia e desenvolvedores sobre interface.

O formato do encontro será no estilo mesa redonda, com frequência mensal e cada edição será realizada em um lugar diferente, de preferência com fácil acesso.

**Valor**: For free! 🎉 

**Mais informações**: http://www.meetup.com/pt-BR/FrontUX/events/230197224/

**Comment by LFeh** [comment]
\o/
