### ISSUE TITLE
[São Paulo] Meetup CSS #15

### ISSUE THREAD

**Issue by LFeh** [frontendbr/eventos#38]
**Título**: Meetup CSS 15
  
**Data**: Terça-feira, 3 de Maio de 2016

**Local**: Rua Beira Rio, 57 , São Paulo

**Descrição**: Para essa edição específica, iremos mudar um pouco o formato e não falaremos especificamente de CSS; o @diegoeis irá falar sobre organização e divisão de times na Locaweb.

**Valor**: Gratuito 

**Mais informações**: http://www.meetup.com/pt-BR/CSS-SP/events/230517971/

![image](https://cloud.githubusercontent.com/assets/3603793/14797948/90e2fc64-0b0b-11e6-9b61-8bd872a90e25.png)

**Comment by raphaelfabeni** [comment]
:metal:
