### ISSUE TITLE
[São Paulo] Meetup #9 - Moip

### ISSUE THREAD

**Issue by LFeh** [frontendbr/eventos#4]
**Título:** Meetup #9 - Moip

**Data:** Terça-feira, 23 de Fevereiro de 2016
19:00 às 21:30

**Local:** R. Jerônimo da Veiga, 248 - Jardim Europa, São Paulo - SP, 04536-001, São Paulo

**Descrição:** O encontro tem o objetivo de promover a troca de conhecimento entre designers e desenvolvedores, aproximar os dois mundos e melhorar o fluxo de trabalho dos profissionais de cada área, possibilitando que designers opinem sobre tecnologia e desenvolvedores sobre interface.

**Valor:** Gratuito

**Mais informações:** http://www.meetup.com/pt-BR/FrontUX/events/228804370/

c/c @matmarsiglio @gmoura

**Comment by gmoura** [comment]
:heart:

**Comment by LFeh** [comment]
Espero que tenha sido ótimo. Queria ter ido =(
