### ISSUE TITLE
[São Paulo] FrontUX #12

### ISSUE THREAD

**Issue by matmarsiglio** [frontendbr/eventos#59]
**Título:** FrontUX Edição 12 no GuiaBolso

**Data:** 31/05/2016

**Local:** Av. Faria Lima, 1656, São Paulo

**Descrição:** O encontro tem o objetivo de promover a troca de conhecimento entre designers e desenvolvedores, aproximar os dois mundos e melhorar o fluxo de trabalho dos profissionais de cada área, possibilitando que designers opinem sobre tecnologia e desenvolvedores sobre interface.

O formato do encontro será no estilo mesa redonda, com frequência mensal e cada edição será realizada em um lugar diferente, de preferência com fácil acesso.

**Valor:** For free! 🎉

**Mais informações:** http://www.meetup.com/pt-BR/FrontUX/events/231043428/

**Comment by LFeh** [comment]
\o

**Comment by willianjusten** [comment]
Eita que eu vou hein!! \o/

**Comment by matmarsiglio** [comment]
@willianjusten mas se vale spoiler, vai ter o de junho!

**Comment by willianjusten** [comment]
Opa, era esse que eu tava esperando @matmarsiglio <3
