### ISSUE TITLE
Algumas correções no responsive

### ISSUE THREAD

**Issue by guuibayer** [frontendbr/eventos#66]
Acredito que podemos colocar um padding nos cards abaixo de 768, e o outro, o before estourou.
![](http://image.prntscr.com/image/609dd02fcb6a4b66883dba0371bd67fb.png)

![](http://image.prntscr.com/image/e9861beca28441189d6c11a189fb4637.png)

**Comment by fdaciuk** [comment]
Boa @guuibayer, obrigado por reportar =) 

O que acha @LFeh? xD

**Comment by LFeh** [comment]
Acho justo. Alias, preciso dar uma verificada geral no layout. Não abri mais depois da implementação.
