### ISSUE TITLE
FEMUG-ABC #11 - AngularJS e WP-API com Ciro Valente

### ISSUE THREAD

**Issue by woliveiras** [frontendbr/eventos#68]
Título: FEMUG-ABC 11 - AngularJS e WP-API com Ciro Valente

Data:

Sábado, 18 de Junho de 2016 as 10:00 às 12:00

Local:

Faculdade Anhanguera de São Bernardo - FASBC
Rua Atlântica, 700, Jardim do Mar, São Bernardo do Campo.
8 Andar, Bloco E, Sala 801

Valor: Gratuito

Mais informações: http://www.meetup.com/pt-BR/femug-abc/events/231207151/

**Comment by fdaciuk** [comment]
Não vai mais ter o evento?

**Comment by woliveiras** [comment]
Vai sim.

Mas como já colocou no site achei que poderia fechar! kkkk

**Comment by fdaciuk** [comment]
Deixa aberto até a galera acostumar com o site xD

**Comment by LFeh** [comment]
Ainda não divulgamos muito @woliveiras :p

**Comment by woliveiras** [comment]
Aaaa

Show de bola caras! 😄

**Comment by devmath** [comment]
Fechem a issue galera, já passou :smile:
