### ISSUE TITLE
Sobre o botão: Anunciar Evento

### ISSUE THREAD

**Issue by woliveiras** [frontendbr/eventos#69]
Galera, poderia ser colocado no botão o seguinte link:

https://github.com/frontendbr/eventos/issues/new

Assim já cai direto na criação da issue.

Que tal?

**Comment by fdaciuk** [comment]
Na real, a ideia desse botão é que o usuário edite o JSON, não adicione uma nova issue xD
Claro que vai ter quem prefira adicionar a issue, mas vamos ter que editar o JSON de qualquer forma pra aparecer no site =)

**Comment by fdaciuk** [comment]
Inclusive, tenho umas ideias pra facilitar isso. Vou criar uma issue xD

**Comment by fdaciuk** [comment]
#70

**Comment by woliveiras** [comment]
Show de bola mano :smile:
