### ISSUE TITLE
Criar backend para o projeto

### ISSUE THREAD

**Issue by fdaciuk** [frontendbr/eventos#70]
Podemos utilizar o [`now`](https://zeit.co/now) para criar um backend para o projeto. Assim, facilitamos pra quem quer cadastrar um novo evento, e não precisamos ficar adicionando manualmente as issues no JSON, nem ficar aprovando alteração no JSON =)

Detalhe: o `now` é free para projetos open source =)

O que acham? 
cc. @frontendbr/admins

**Comment by LFeh** [comment]
Acho que vale a pena sim @fdaciuk!

**Comment by angeliski** [comment]
Precisam de ajuda com isso ai galera?

**Comment by theandersonn** [comment]
@angeliski Sempre! :heart_eyes:

Tem algo em mente? 

O @felipeuntill chegou a montar uma cli que tal trocar uma ideias?

Na minha opinião, o que mais vai se adequar é ter um crud para facilitar o gerenciamento dos eventos e facilitar que novos colaboradores utilizem.

**Comment by felipeuntill** [comment]
Eu consigo provisionar uma verba mensal de até 50 doletas para infra.

**Comment by LFeh** [comment]
@theandersonn Se se sentir confortável, pode tocar esse projeto, confio em suas decisões 😉

**Comment by angeliski** [comment]
Então, eu pensei que a gente poderia usar o Firebase nessa questão de armazenamento dos eventos, e fazer um back em node simples só pra gerenciar algumas coisas. 
Dependendo do tráfego do site (que vocês devem ter uma ideia melhor que eu) o plano free deve ser o suficiente.

**Comment by angeliski** [comment]
Eu criei um repositório separado pra dar o start e fiz um draft da minha ideia da API no Swagger.
https://github.com/angeliski/frontendbr-eventos-api
Se vocês quiserem avaliar é só seguir o README que tá fácil.

**Comment by theandersonn** [comment]
@LFeh Ainda não me sinto confortável pra tocar essa feature, seria um grande prazer. E tbm tem o fato de eu estar um tanto sobrecarregado com a entrega de TCC na faculdade.

**Comment by fdaciuk** [comment]
Legal @angeliski! Essa issue estava quase fazendo aniversário xD
Acha que consegue tocar esse projeto inteiro ou precisa de ajuda?

**Comment by diogomoretti** [comment]
Daria para usar também o [Wedeploy](http://wedeploy.com). Poderíamos falar com o Zeno para ver como fica para OSS =]

**Comment by angeliski** [comment]
@fdaciuk Eu acho que consigo tocar isso tranquilamente, minha maior preocupação é definir algumas direções pra não fazer um negócio meio sem uso prático. 
Por exemplo, vocês precisam que esse backend tenha autenticação? Em caso positivo, pode ser um JWT ou precisa de um oauth2? Algum problema em usar o Firebase (Eu até tenho em mente criar uma pequena abstração pra caso seja necessário trocar de banco, mas preferia fazer com um foco logo de cara) ? 
Eu vou montar um pequeno Planning e criar as Issues nesse repositório, assim fica transparente o progresso e se alguém quiser participar também fica mais a vontade.

@felipeuntill Você vê alguma necessidade especifica que a API precise ter pra atender o CLI que você está montando?

**Comment by fdaciuk** [comment]
Quando eu criei a issue eu tinha pensado em algo que fosse o mais simples possível:
- backend com Firebase mesmo;
- deploy no now (gratuito);
- Formulário no frontend, com login social (só GitHub);

Uma validação no backend pra aprovar as vagas: login com GitHub padrão, mas validando pelo userId.. dá pra pegar os userIds da galera da organização, se for alguém que logou, ter um "admin" pra aprovar / desaprovar o evento (desaprovar no caso de spam).

Ae a aplicação atual consumiria do backend ao invés do JSON como está hoje.

Então o trabalho ficaria somente em aprovar / desaprovar e cadastrar os eventos, ao invés de ter que ficar atualizando o JSON e fazendo deploy a todo momento.

**Comment by angeliski** [comment]
Show! Com isso eu consigo ter uma ideia de pra onde ir.
Só uma pergunta, você prefere que a questão de aprovar / desaprovar e cadastrar os eventos seja a parte? Porque eu estava pensando em fazer a API em um projeto e usar o próprio site dos eventos para implementar esse "consumo" das APIS.
Desse modo, teriamos a API em um projeto e toda a questão do Front nesse repositório mesmo, só muda que agora existiria um "Dashboard" pros Adms. Que acha?

**Comment by fdaciuk** [comment]
Sim, o consumo vai ser direto no site já existente. Só vamos mudar que, ao invés de consumir do JSON, ele consome dessa API do backend. Ae teria só que fazer uma dashboard simples pra cadastro e aprovação dos eventos, mas nada além de um form simples pra quem form cadastrar, e uma lista desses eventos com um checkbox pra aprovar =)

**Comment by angeliski** [comment]
Maravilha @fdaciuk 
Eu estou fazendo alguns testes de arquitetura e algumas configurações com o Travis, mas até o fim da semana eu já devo conseguir disponibilizar a estrutura inicial e as Issues. Qualquer problema eu sinalizo. 👍

**Comment by angeliski** [comment]
Salve @fdaciuk Eu terminei de configurar a estrutura e o deploy no Now, se você quiser olhar a documentação do Swagger pode acessar aqui: https://frontendbr-eventos.now.sh/api/docs/

Só que no levantamento de tarefas me bateu uma dúvida.  
A ideia é o usuário fazer o login, via github, no site. Só que, como eu vou transportar esse login para api e por consequência para o Firebase? 
Ele até tem um provider de login do Github, mas pelo que eu vi o firebase teria q providenciar esse provider e não o site... Não sei se a dúvida ficou clara XD

Será que você já fez algo do tipo?

**Comment by fdaciuk** [comment]
Ficou bem legal a API @angeliski, parabéns :dancer: :dancer: :sparkles: 

Na real, a ideia não é fazer no site que existe hoje.. O que precisa ser feito é:
- fazer um backend (que pode ser junto com essa API que você já fez);
- fazer um frontend com um formulário para cadastro dos eventos, que bate nesse backend para salvar os dados no Firebase;
- e o site que temos hoje deve consumir os eventos do Firebase, mas não diretamente; vai ser à partir desse backend.

Dessa forma, independe se o login é via Firebase ou usando o Passport, pois o login vai ser validado no backend. Acho melhor validar no backend do que deixar essas regras no Firebase, que assim a gente centraliza isso se precisar mudar de banco amanhã =)

E no backend a gente usa o `firebase-admin` pra gravar os dados na base.

Ficou claro? =)

**Comment by angeliski** [comment]
Vamos ver se eu entendi @fdaciuk 
No backend, eu vou disponibilizar uma URL de login: Ex: https://frontendbr-eventos.now.sh/auth
Assim, o cara que quiser logar vai fazer isso batendo nessa url, cai no flow do Github e segue vida.

Dai todo o resto é consumido do backend, via API, levando em conta o login que o cara já fez.
Os endpoints de listagem não precisam de autenticação (evitando que o usuário tenha q logar pra ver os eventos), os endpoints de criação / aprovação precisam de login.

Confere?

**Comment by fdaciuk** [comment]
Quase isso. Vamos lá:

São duas aplicações:

## 1. Site de eventos (já temos hoje)

O site de eventos que já temos hoje consome os eventos de um JSON. Agora ele vai passar a consumir da segunda aplicação, que é essa API que você já fez.

## 2. Cadastro de eventos

Nessa segunda aplicação, precisamos de:
- Um frontend, com um formulário para cadastrar um evento. Para cadastrar, precisa estar logado no GitHub;
- Um backend para validar o login, e fazer o cadastro;

As regras para essa aplicação seriam:
- Se algum dos moderadores logarem, deve aparecer a lista de eventos para aprovar/desaprovar, além do formulário para cadastrar um novo evento;
- Se qualquer pessoa que não seja moderador logar, só vai ver o formulário de cadastro. Ao cadastrar, deve ter alguma flag para saber se esse evento foi aprovado ou não;
- Quando um moderador aprovar algum evento, mudar a flag de aprovação conforme a opção selecionada (aprovado / não aprovado);
- O site de eventos vai consumir desse backend os eventos (só GET), e só deve receber os eventos que estiverem aprovados.

---

Acho que é isso! Se alguém tiver alguma outra consideração, fique à vontade =)

@angeliski se quiser, pode criar aqui no GitHub mesmo, na aba "Projects" os cards para essas tarefas, para ficar mais fácil de separar e entender o que precisa ser feito, e no que você precisa de ajuda. Acho que assim fica tranquilo de se organizar =)

**Comment by angeliski** [comment]
Show de bola @fdaciuk !
Agora eu finalmente entendi que são duas aplicações separadas ! XD
Eu achei que tudo ia ser feito no front da aplicação que existe hoje.
Com isso eu consigo montar os cards de boa. Valeu!

**Comment by angeliski** [comment]
Salve galera! Eu já implementei algumas coisas (bastante até). Será que vocês poderiam dar uma olhada no código e me dar um feedback? Como eu não tenho experiência em node nem no Firebase, talvez tenha uma forma melhor de fazer isso.... Enfim, segue o repositório:
https://github.com/angeliski/frontendbr-eventos-api

**Comment by mesafael** [comment]
Fala galera beleza?
Sou Dev Front, faz tempo que gostaria de ajudar a comunidade e não sei por onde começar, aproveitando que estou desempregado vi que vocês estão com esse projeto, posso ajudar de alguma forma?

**Comment by angeliski** [comment]
Salve @mesafael ! Pode ajudar sim! Eu estou desenvolvendo atualmente a parte da API, se você quiser ajudar será muito bem vindo. Você tem experiência com Node/Firebase? Eu não tenho... XD
Então se você quiser dar uns pitacos na minha estrutura/ código sinta-se a vontade!
https://github.com/angeliski/frontendbr-eventos-api
Se você não tiver experiência com node/firebase também, pode ajudar na parte do front mesmo, a gente ainda tem que fazer o cadastro ,dashboard admin e afins. Eu criei algumas issues no repositório, mas se tiver confuso ou você precisar de alguma orientação pode perguntar que eu ajudo dentro do possível. ;)

**Comment by angeliski** [comment]
Salve @fdaciuk 
Cara, eu basicamente terminei o backend, agora falta só fazer o portal onde serão feitos os cadastros e a administração. Eu optei por fazer um publicar no WeDeploy, porque no Now o código fica exposto, e eu não posso expor as chaves do firebase admin. Eles até tem um esquema de secrets para variável de ambiente (que eu inclusive uso no WeDeploy), mas pra valores muito grandes, não rola.

Enfim, só pra dar um status, quem quiser dar uma revisada no código, pode ficar a vontade.

Abraço!

**Comment by LFeh** [comment]
@frontendbr/admins @frontendbr/eventos

**Comment by fdaciuk** [comment]
Legal @angeliski! Não vou conseguir olhar essa semana, mas tento dar uma olhada com calma na próxima :D 

Parabéns pelo trampo :D

**Comment by angeliski** [comment]
Valeu @fdaciuk ! Eu sei q o código podia ser melhor porque eu não tenho experiência com aplicações em node, mas é um primeiro passo já! 👍 
Eu já comecei a fazer o Front também, quando tiver pronto eu já faço o link aqui pra vocês darem uma olhada.

**Comment by vmarcosp** [comment]
@angeliski Precisa de uma mãozinha ? Tenho experiência com Node 😄

**Comment by angeliski** [comment]
Opa @vmarcosp , eu meio que "já terminei" o que eu tinha me proposto a fazer. Se você puder dar uma revisada, umas dicas e tal, eu posso ir ajustando. :)
https://github.com/angeliski/frontendbr-eventos-api

**Comment by vmarcosp** [comment]
@angeliski Claro, vou fazer um fork e vamos conversando sobre isso.

**Comment by lucaspalencia** [comment]
@vmarcosp @angeliski se puderem manter a conversa por aqui ou criando uma issue direto no repositório do projeto, agradecemos :smile:

Eu comecei a estudar node a pouco tempo e semana passada estava fazendo uns testes no projeto, gostaria de acompanhar as sugestões pra aprender um pouco mais.

**Comment by angeliski** [comment]
Sem problemas @lucaspalencia ! Eu também não sei muito da coisa toda não, mas é uma boa hora pra gente aprender :) Acho melhor a gente ir abrindo issues por lá mesmo, pra manter mais "junto" as atualizações. O que se acha @vmarcosp ?

**Comment by vmarcosp** [comment]
@angeliski @lucaspalencia  Claro ótima ideia, assim todos acompanham o andamento do projeto. Essa semana ainda vou revisar a api pra realizarmos melhorias 😄

**Comment by vmarcosp** [comment]
Em relação ao dash da aplicação eu e o @angeliski pensamos em fazer algums mockups das telas pra ver se todos estão de acordo. Ou de repente se alguém puder dar uma mão nessa parte de UX e UI, seria muito bem vindo 👍 .

**Comment by vmarcosp** [comment]
@theandersonn @fdaciuk @LFeh Em relação ao dashboard, foi tomada alguma decisão em relação a tecnologias ? Outra coisa, para tratar do front-end seria boa criar uma outra issue ?

**Comment by theandersonn** [comment]
@vmarcosp  Sobre o dashboard pelo que tenho acompanhado não vi nada, mas o @angeliski pode dar um feedback mais assertivo. E quanto as tarefas de front, podem criar um nova issue, sem problemas. Precisando de label, se desejarem organizar com milestone, é só falar que vamos ajudando.

**Comment by LFeh** [comment]
@angeliski Voce move seu repositorio pra dentro da org para concentrar tudo aqui dentro?
Vou te colocar como moderador desse repositorio, assim você trabalha livremente.

@vmarcosp Nunca mais falamos disso na verdade.

Você vai acompanhando @theandersonn?

**Comment by vmarcosp** [comment]
@theandersonn Legal, vou abrir uma nova issue para o front-end. Tenho mantido contato com o @angeliski sobre esse projeto e combinamos de manter tudo aqui no fórum para ter uma dar uma boa visibilidade.

**Comment by LFeh** [comment]
Esse repositorio de Eventos é o @theandersonn que manda 😄

**Comment by angeliski** [comment]
Opa @LFeh Posso transferir sim, só preciso do acesso pra mover ele

**Comment by LFeh** [comment]
Feito!

**Comment by angeliski** [comment]
@LFeh Eu já aceitei, mas ainda aparece permissão negada na hora de transferir. Tenho q fazer mais alguma coisa?

**Comment by LFeh** [comment]
Ahhhhh, então, good point. Achei que ia transferir pra dentro desse repositorio.

@frontendbr/admins Acham melhor deixar a API em outro repositorio?

**Comment by angeliski** [comment]
Ih, perai. Acho que eu não entendi bem então. A ideia é ter a API dentro do **frontendbr/eventos** como um subfolder mesmo? Eu achei que iria ser um repositorio a parte... Se for esse o caso, acho que seria melhor ter uma separação mais top level, do que é api, o front do site e o o front do admin, não?

**Comment by fdaciuk** [comment]
@LFeh a API tem ficar num repo separado mesmo.. o repo de eventos é especificamente o site dos eventos. Ele vai consumir a API, mas a API vai ser um projeto separado mesmo. Até porque, o terceiro projeto seria a "dashboard" (ou como quiserem chamar), que vai servir para cadastrar os eventos na API.

Então sim, o ideal é ficar em um repo à parte :)

**Comment by LFeh** [comment]
Vou criar e colocar o @angeliski pra administrar então ;)

**Comment by LFeh** [comment]
@angeliski Tenta agora ;)

**Comment by angeliski** [comment]
@LFeh Ainda com permissão insuficiente

**Comment by theandersonn** [comment]
@angeliski A opção de Two-factor authentication está habilitada?

**Comment by angeliski** [comment]
Tá sim @theandersonn . Ele só permitiu que eu aceitasse o convite do @LFeh com ela ativada. Mas parece que tem que ter permissão pra criar o repositório em si mesmo

**Comment by LFeh** [comment]
De novo :p

**Comment by angeliski** [comment]
Opa, agora foi. Transferi já. Vocês preferem que mova o front dele já também? (Que eu chamei Portal XD)
https://github.com/angeliski/frontendbr-eventos-portal

**Comment by LFeh** [comment]
1. Perfeito, já mudei o nome para `eventos-api`
2. Pode mover, e depois muda o nome para `eventos-dashboard`
3. Vou fechar essa issue. Vamos tratar tudo dentro dos repositorios agora!

Sucesso e valeu mano.

**Comment by angeliski** [comment]
@LFeh Movi o outro repositório. Só que agora eu não consigo fazer mais "nada" nele, com relação a tagear as issues e mover os cards do project. Se pode liberar essa permissão pra mim?

**Comment by LFeh** [comment]
Vou colocar.

**Comment by LFeh** [comment]
Tenta agora @angeliski

**Comment by angeliski** [comment]
@LFeh Deu certo no dashboard, mas não no da api

**Comment by LFeh** [comment]
Agora vai!

**Comment by angeliski** [comment]
Sucesso @LFeh !
