### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by LFeh** [frontendbr/eventos#72]
Can you include @fdaciuk?

**Comment by fdaciuk** [comment]
i've already did this xD
https://github.com/frontendbr/eventos/blob/develop/src/img/favicon.png

**Comment by LFeh** [comment]
\o/

**Comment by fdaciuk** [comment]
It's needed to change on template file, removing the slash at the beginning from the path: 
https://github.com/frontendbr/eventos/blob/develop/src/templates/index.ejs#L8
