### ISSUE TITLE
FrontinNatal

### ISSUE THREAD

**Issue by yuriscosta** [frontendbr/eventos#74]
**Título**: FrontInNatal
  
**Data**: 09/07

**Local**: IFRN - Campus Natal Central

**Descrição (breve)**: 
O evento é voltado para todo e qualquer estudante ou profissional da área de designer gráfico à desenvolvedor de software que atue na área de FrontEnd ou que deseje entrar neste mercado que cresce exponencialmente a cada dia que passa. 
O evento será realizado durante todo o dia e será composto por diversas palestras sobre temas variados dentro do contexto e tecnologias no qual o evento está relacionado. Em paralelo as palestras iremos realizar uma atividade inédita chamada DojoInTheDark que ainda é um mistério de como irá funcionar, mas temos certeza de que será bastante divertido e que vocês irão gostar. 

**Valor**: Lista com valores: http://www.eventick.com.br/frontinnatal

**Mais informações**:

**Comment by LFeh** [comment]
\o/
