### ISSUE TITLE
[Campinas] Campinas Front-End Meetup #5

### ISSUE THREAD

**Issue by victormiguez** [frontendbr/eventos#8]
**Título**: Front-End Meetup *#*5
  
**Data**: Quinta-feira, 27 de Fevereiro de 2016
14:00 às 18:00

**Local**: CDI Campinas (Minha Campinas) - Av. Nestor Castanheira, 201, Campinas

**Descrição (breve)**: O meetup foca na troca de experiências entre os participantes. Dessa vez contaremos com o [Luís Felipe](https://twitter.com/luisfmsouz) falando sobre PostCSS e depois faremos uma mesa redonda com assuntos variados.

**Valor**: Gratuito

**Mais informações**: http://www.meetup.com/pt-BR/Campinas-Front-End-Meetup/events/228639046/

**Comment by LFeh** [comment]
Muito bom @victormiguez :)

**Comment by eduardojmatos** [comment]
@victormiguez <3

**Comment by luisfmsouza** [comment]
é nóis :metal:

**Comment by BielRibeiro** [comment]
Nos vemos lá :smiley:
