### ISSUE TITLE
2° Meetup CSS PoA

### ISSUE THREAD

**Issue by leonardo403** [frontendbr/eventos#88]
**Título**: 2° Meetup CSS PoA
  
**Data**: Quinta-feira, 28 de Julho de 2016

**Local**: ThoughtWorks Brasil
Avenida Ipiranga 6681 - Prédio 99a (TECNOPUC) - 14 Andar - Sala Brasil, Porto Alegre (**[map](https://maps.google.com/maps?f=q&hl=en&q=Avenida+Ipiranga+6681+-+Pr%C3%A9dio+99a+%28TECNOPUC%29+-+14+Andar+-+Sala+Brasil%2C+Porto+Alegre%2C+br)**)

**Talks**:
1ª - **[Felipe Morais](https://github.com/lipemorais)** 
Sass, um pre-processador CSS que facilita muito a vida de quem quer deixar o seu CSS bem organizado
2ª - **[Leonardo Lima](https://github.com/leonardo403)** 
A essência do CSS

**Valor**: Gratuito

**Programação**:
19:00 - Abertura 

19:05  - Primeira talk - **[Felipe Morais](https://github.com/lipemorais)** 

20:35 - Segunda talk - **[Leonardo Lima](https://github.com/leonardo403)** 

21:05 - Coffee break/networking  

21:20 - Envie sua talk - **[bit.ly/meetup-css-poa](https://bit.ly/meetup-css-poa)**

**Comment by woliveiras** [comment]
@leonardo403 o link para mais informações é o mesmo do `envie sua talk`?

**Comment by leonardo403** [comment]
Dúvidas sobre o Meetup CSS tem que ser enviadas a eles.

[Filipe Linhares](https://twitter.com/ofilipelinhares) | [Ana Schwendler](https://twitter.com/anaschwendler)
