### ISSUE TITLE
O que vocês acham da criação de um evento focado JS aqui em SP?

### ISSUE THREAD

**Issue by fernandofleury** [frontendbr/eventos#9]
Não sei se é o local correto pra dissertar no assunto, mas vamos lá:

Acho que a CSS Conf trouxe uma visibilidade muito bacana pra CSS, e acredito que isso possa ser espelhado pra JS também.

Existe algo nesse nível aqui em SP? Se não, não podemos organizar isso?

**Comment by eduardojmatos** [comment]
@fernandofleury cara, tem um meetup (JSSP) que tá começando agora: http://www.meetup.com/Javascript-SP/events/228548977/ e aqui no BankFacil (olha o jabá huahua)

Mas realmente, uma conf de JS não tem... Bora fazer? Hehhehe

Um evento que estou sentindo falta é o JS Conf. Será que morreu? http://2014.jsconfbr.org/

O último foi em 2014 #xatiado

**Comment by elvisdetona** [comment]
SampaJS... mas deu uma parada :disappointed:

**Comment by eduardojmatos** [comment]
@elvisdetona Verdade. Tinha um SampaJS

**Comment by fernandofleury** [comment]
O suissa comentou sobre tentar fazer lá pro meio do ano, mas poderíamos ter algo mais assertivo. O que acham de trocar uma ideia com ele? Sinto falta de algo com o nível da CSS Conf.

**Comment by victormiguez** [comment]
@eduardojmatos @elvisdetona caras, esses tempos atrás eu vi o Suissa comentando no facebook sobre reviver o evento, mas não sei em que pé está isso.
Vocês chegaram a ver os posts dele?

**Comment by eduardojmatos** [comment]
@fernandofleury @victormiguez @elvisdetona eu topo.

@suissa e aí mano? Quando é que vai rolar esse SampaJS marotão ae? BORA! :)

**Comment by eduardojmatos** [comment]
@victormiguez boa boa. Podemos pensar nisso aí. cc @elvisdetona

**Comment by elvisdetona** [comment]
@victormiguez @eduardojmatos @fernandofleury  Se o @suissa liberar e nos der "liberdade" pra correr atrás e fazer o evento acontecer... ALGUEM tem que tomar a frente. 

Eu e @deividmarques estamos meeeeeega enrolados com a CSS CONF e Frontinsampa...  no meu caso, eu posso ajudar, mas não CONSIGO segurar a responsabilidade de mais um evento, mas posso ajudar no que for preciso. E o @deividmarques "se puder", pode segurar a bronca com vcs ahuauhahuahua.

Eae Suissinha, libera o evento pros bródi agitar a comunidade! 
Sdds SampaJS

**Comment by eduardojmatos** [comment]
Huahuauha boa @elvisdetona 

Vc e o @deividmarques já manjam dos paranauês de eventos mano. Podem ajudar e adicionar "colaboradores" ou "voluntários" pra tocar a parada :)

**Comment by fernandofleury** [comment]
Boa!

**Comment by eduardojmatos** [comment]
@fernandofleury sim, vamoae

**Comment by fernandofleury** [comment]
Vou trocar uma ideia com o suissa

**Comment by leandrogrillo** [comment]
suissa vai tocar pro pai @fernandofleury e ele resolve

**Comment by Mendrone** [comment]
Eu acho a ideia sensacional, bora trocar ideia com o Suissa e tirar isso do papel! :smile:

**Comment by LFeh** [comment]
Do carario. 

Ter Meetup focado em JavaScript é fodastico também. Já estou participando, vou tentar ir nas proximas edições!

**Comment by kivervinicius** [comment]
@theandersonn why?
