### ISSUE TITLE
MeetupCSS #19

### ISSUE THREAD

**Issue by theandersonn** [frontendbr/eventos#95]
**Título**: MeetupCSS 19
  
**Data**:  Quinta-feira, 25 de Agosto de 2016

**Local**: Rua Vergueiro, 3185, Sao Paulo (Auditório Caelum)

**Valor**: Gratuito

**Programação**:
19:30 - 20:00 => Coffee Break
20:00 - 21:00 => Talk do Marco Bruno: Posicionando as coisas na tela com CSS
21:00 - 21:45 => Debate 

**Mais informações**: http://www.meetup.com/pt-BR/CSS-SP/events/233231383/?eventId=233231383 

![cpqgwayw8aapzy3](https://cloud.githubusercontent.com/assets/5203138/17630172/8f047a7e-6094-11e6-9de8-12190a74ce43.jpg)

**Comment by LFeh** [comment]
@raphaelfabeni

**Comment by raphaelfabeni** [comment]
:metal:  💀
