### ISSUE TITLE
[São Bernardo do Campo - SP] ABCDev - 2016

### ISSUE THREAD

**Issue by woliveiras** [frontendbr/eventos#99]
**Título**: ABCDev - 2016
  
**Data**: 17 Setembro 2016

**Local**: HP Imigrantes - Estrada Samuel Aizemberg, 1707 - Alves Dias,
São Bernardo do Campo - SP, CEP 09851-550

**Descrição (breve)**: A primeira conferência sobre Desenvolvimento do Grande ABC

**Valor**: 35, 50 e 65,00

**Mais informações**: Uma conferência para mostrar a força dos desenvolvedores do ABC.

**Comment by theandersonn** [comment]
Uai @woliveiras :anguished:
Já está até no json: https://github.com/frontendbr/eventos/issues/77

**Comment by woliveiras** [comment]
Vish! Mosquei @theandersonn UUHAHUAHU

Foi mal

Fechando
